### ISSUE TITLE
Turn-based game

### ISSUE THREAD

**Issue by oreyabak** [alvyxaz/barebones-masterserver#100]
Hello.

I'm creating a turn-based game 1v1.
This game does not need a continuous connection, only when one player finishes his turn is when the other player is updated.

Is there an example?

Greetings.

**Comment by angusmf** [comment]
Greetings!

This is really a game implementation question. In general, with a turn-based game, your player will send a message to the game server when their turn is over. You can implement that with any networking you want, including creating your own messages in MSF. MSF uses sockets, so connections are "continuous" but traffic is only sent when you send a message.

**Comment by oreyabak** [comment]
thank for lnformation.
