### ISSUE TITLE
Failed to log in (ValidatePassword) 

### ISSUE THREAD

**Issue by VergilUa** [alvyxaz/barebones-masterserver#106]
Hi, so this one is quite critical. I'm unable to login with Msf.Client.Auth.LogIn when I'm using actual login and password (non-guest). 

I've checked registered password in database (I'm switched to PostgreSQL) and the one that used for the check is identical. I've also checked if received password is correct, and it is.

However it seems that MsfSecurity.ValidatePassword is generating wrong testHash for the actual check. (I've also used a custom method to confirm that those arrays are not equal).  I might be wrong about the cause though, but it's 100% that ValidatePassword returns false all the time, even if proper password is passed.

Is there something that can be done?

My current setup for MSF:
Two separate projects for client/server;
PostgreSQL Db;
Custom AuthModule;
Everything else seems unchanged from original.

**Comment by alvyxaz** [comment]
Hey! Thanks for reporting, I'll check it out shortly ;)

**Comment by alvyxaz** [comment]
I did a quick test, and everything seems to be working fine, when using the default auth module (password  `#FaA~K#9TYLt/(9`)

Can you send me a password you've tried and failed? Maybe it's a special character that get's screwed up when encoding a string.

Also, can you paste in the complete password field value from database?

**Comment by VergilUa** [comment]
I haven't put any special characters, only simple "test" password. I've generated two similar "test" password for two different accounts:

1000:b+hRDkZKcMLQxeKTxiLYoBh094yKAaQM:1fO6hY6ECXbF8qKHlYp3w82gdQOUon1s
1000:GsCgzJD/O5HZ0qA8jSNy4S8XdWtYyJMO:LvD5PM3hEfSF+CQQTSTIHJKGfYgSV5XO

**Comment by VergilUa** [comment]
My custom AuthModule:

`using System;
using System.Collections.Generic;
using System.Linq;
using Barebones.MasterServer;
using Barebones.Networking;
using UnityEngine;

namespace Server.CustomModules {
    public class SecureAuthModule : AuthModule {
        /// <summary>
        /// Handles a request to log in
        /// This is the same implementation, but includes email confirmation
        /// </summary>
        /// <param name="message"></param>
        protected override void HandleLogIn(IIncommingMessage message) {
            if (message.Peer.HasExtension<IUserExtension>()) {
                message.Respond("Already logged in", ResponseStatus.Unauthorized);
                return;
            }

            var encryptedData = message.AsBytes();
            var securityExt = message.Peer.GetExtension<PeerSecurityExtension>();
            var aesKey = securityExt.AesKey;

            if (aesKey == null) {
                // There's no aesKey that client and master agreed upon
                message.Respond("Insecure request".ToBytes(), ResponseStatus.Unauthorized);
                return;
            }

            var decrypted = Msf.Security.DecryptAES(encryptedData, aesKey);
            var data = new Dictionary<string, string>().FromBytes(decrypted);

            var db = Msf.Server.DbAccessors.GetAccessor<IAuthDatabase>();

            IAccountData accountData = null;

            // ---------------------------------------------
            // Guest Authentication
            if (data.ContainsKey("guest") && EnableGuestLogin) {
                var guestUsername = GenerateGuestUsername();
                accountData = db.CreateAccountObject();

                accountData.Username = guestUsername;
                accountData.IsGuest = true;
                accountData.IsAdmin = false;
            }

            // ----------------------------------------------
            // Token Authentication
            if (data.ContainsKey("token") && accountData == null) {
                accountData = db.GetAccountByToken(data["token"]);
                if (accountData == null) {
                    message.Respond("Invalid Credentials".ToBytes(), ResponseStatus.Unauthorized);
                    return;
                }

                var otherSession = GetLoggedInUser(accountData.Username);
                if (otherSession != null) {
                    otherSession.Peer.Disconnect("Other user logged in");
                    message.Respond("This account is already logged in".ToBytes(),
                                    ResponseStatus.Unauthorized);
                    return;
                }
            }

            // ----------------------------------------------
            // Username / Password authentication

            if (data.ContainsKey("username") && data.ContainsKey("password") && accountData == null) {
                var username = data["username"];
                var password = data["password"];

                accountData = db.GetAccount(username);

                if (accountData == null) {
                    // Couldn't find an account with this name
                    message.Respond("No such user found".ToBytes(), ResponseStatus.Unauthorized);
                    return;
                }
                
                //******************** It fails here ****************
                if (!Msf.Security.ValidatePassword(password, accountData.Password)) {
                    // Password is not correct
                    message.Respond("Invalid password".ToBytes(), ResponseStatus.Unauthorized);
                    return;
                }
            }

            if (accountData == null) {
                message.Respond("Invalid request", ResponseStatus.Unauthorized);
                return;
            }

            if (!accountData.IsEmailConfirmed) {
                // Email address not yet confirmed, so let's try to confirm it now...
                if (data.ContainsKey("confirmationCode")) {
                    var confirmationCode = data["confirmationCode"];
                    if (db.GetEmailConfirmationCode(accountData.Email) != confirmationCode) {
                        message.Respond("Incorrect confirmation code".ToBytes(), ResponseStatus.UnconfirmedAccount);
                        Logs.Warn("PASSWORD AUTHENTICATION failed. Incorrect confirmation code for account: - "
                                  + accountData.Username);
                        return;
                    }

                    // now the email confirmation code is confirmed
                    accountData.IsEmailConfirmed = true;
                    db.UpdateAccount(accountData);

                    // need to remove row from db email_confirmation_codes
                    db.SaveEmailConfirmationCode(accountData.Email, string.Empty);

                    // Invoke the event
                    OnEmailConfirmed(accountData);
                } else {
                    message.Respond("No confirmation code sent".ToBytes(), ResponseStatus.UnconfirmedAccount);
                    Logs.Warn("PASSWORD AUTHENTICATION failed. Incorrect confirmation code for account: - "
                              + accountData.Username);
                    return;
                }
            }

            // Setup auth extension
            var extension = message.Peer.AddExtension(CreateUserExtension(message.Peer));
            extension.Load(accountData);
            var infoPacket = extension.CreateInfoPacket();

            // Finalize login
            FinalizeLogin(extension);

            message.Respond(infoPacket.ToBytes(), ResponseStatus.Success);
            return;
        }
        
        /// <summary>
        /// Handles account registration request
        /// </summary>
        /// <param name="message"></param>
        protected override void HandleRegister(IIncommingMessage message)
        {
            var encryptedData = message.AsBytes();

            var securityExt = message.Peer.GetExtension<PeerSecurityExtension>();
            var aesKey = securityExt.AesKey;

            if (aesKey == null)
            {
                // There's no aesKey that client and master agreed upon
                message.Respond("Insecure request".ToBytes(), ResponseStatus.Unauthorized);
                return;
            }

            var decrypted = Msf.Security.DecryptAES(encryptedData, aesKey);
            var data = new Dictionary<string, string>().FromBytes(decrypted);

            if (!data.ContainsKey("username") || !data.ContainsKey("password") || !data.ContainsKey("email"))
            {
                message.Respond("Invalid registration request".ToBytes(), ResponseStatus.Error);
                return;
            }

            var username = data["username"];
            var password = data["password"];
            var email = data["email"].ToLower();

            var usernameLower = username.ToLower();

            var extension = message.Peer.GetExtension<IUserExtension>();

            if (extension != null && !extension.AccountData.IsGuest)
            {
                // Fail, if user is already logged in, and not with a guest account
                message.Respond("Invalid registration request".ToBytes(), ResponseStatus.Error);
                return;
            }

            if (!IsUsernameValid(usernameLower))
            {
                message.Respond("Invalid Username".ToBytes(), ResponseStatus.Error);
                return;
            }

            if (Config.ForbiddenUsernames.Contains(usernameLower))
            {
                // Check if uses forbidden username
                message.Respond("Forbidden word used in username".ToBytes(), ResponseStatus.Error);
                return;
            }

            if (Config.ForbiddenWordsInUsernames.FirstOrDefault(usernameLower.Contains) != null)
            {
                // Check if there's a forbidden word in username
                message.Respond("Forbidden word used in username".ToBytes(), ResponseStatus.Error);
                return;
            }

            if ((username.Length < Config.UsernameMinChars) ||
                (username.Length > Config.UsernameMaxChars))
            {
                // Check if username length is good
                message.Respond("Invalid username length".ToBytes(), ResponseStatus.Error);

                return;
            }

            if (!ValidateEmail(email))
            {
                // Check if email is valid
                message.Respond("Invalid Email".ToBytes(), ResponseStatus.Error);
                return;
            }

            var db = Msf.Server.DbAccessors.GetAccessor<IAuthDatabase>();

            var account = db.CreateAccountObject();

            account.Username = username;
            account.Email = email;
            account.Password = Msf.Security.CreateHash(password);
            
            try
            {
                db.InsertNewAccount(account);

                OnRegistration(message.Peer, account);

                message.Respond(ResponseStatus.Success);
            }
            catch (Exception e)
            {
                Logs.Error(e);
                message.Respond("Username or E-mail is already registered".ToBytes(), ResponseStatus.Error);
            }
        }
    }
}
`

**Comment by VergilUa** [comment]
Well, I've managed to output testHash and the actual hash arrays. They seems to majorly differ. I guess there's something wrong with the testHash generation method. Idk what though.

testHash
173 153 81 157 72 176 44 203 150 60
64 204 243 110 115 55 127 159 146 155
19 255 151 71

actual hash
213 243 186 133 142 132 9 118 197 242
162 135 149 138 119 195 205 160 117 3
148 162 125 108

**Comment by VergilUa** [comment]
Wow
I feel dumb. For some reason I was passing **** instead of password. My godness.
