### ISSUE TITLE
string limit with SerializablePacket object?

### ISSUE THREAD

**Issue by Berserk974** [alvyxaz/barebones-masterserver#108]
Hi guy(s) ,
You made a wonderfull work with this asset, i really love it, thanks to you i understand a little more everydays.

But now i have a little problem to progress with my project, so i wish you or anyone else can help me.
i try to send  a simple string "00 00 00 00 00 00 00 00 00 00" from server to client but the client can"t read all the stream , there is the error : 
"EndOfStreamException: End of stream reached with 229 byte left to read." 

there is my code for this custom message : 

```
using Barebones.Networking;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using myUtils;
public class myCustomMessage: SerializablePacket
{
    public int opCode;
    public int choice;
    public string allCards;

public override void FromBinaryReader(EndianBinaryReader reader)
    {
        opCode = reader.Read7BitEncodedInt();
        choice = reader.ReadInt16();
        allCards =reader.ReadString();

    }

    public override void ToBinaryWriter(EndianBinaryWriter writer)
    {
        writer.Write(opCode);
        writer.Write(choice);
        writer.Write(allCards);
    }


}
```

and this is how i send message : 
```
           myCustomMessagemessage = new myCustomMessage()
 {
                opCode = (short)TfInGameOpCode.hand,
                choice = -1,
                allCards = getStringCard(cardsInHand) // = "00 00 00 00 00 00 00 00 00 00" if i trust the visual studio debbuger
            };
```

So anyone know how can i solve this?

Thanks

**Comment by Berserk974** [comment]
i found that int can only be read by readint32() :/

**Comment by alvyxaz** [comment]
Hey!

Haha, the problem was that you wrote 32bit int (default), and read it as 7BitEncodedInt (there's a separate write method for it).

If you want to save space, you can define your opCode as byte (if value doesn't go over the byte limit) ;)
`public byte opCode`

**Comment by Berserk974** [comment]
well thanks to you i use only byte and byte[] ffor every message now and everything work perfectly^^
