### ISSUE TITLE
cant use it on mac os

### ISSUE THREAD

**Issue by delmarle** [alvyxaz/barebones-masterserver#11]
im using unity 5.4.1 and when i start unity using sudo /Applications/Unity/Unity.app/Contents/MacOS/Unity

it works nicely. there is 2 problem however:
in monobehaviour some stuff dont load correctly:

https://gyazo.com/3d6f3fbab54474f560a4175d7e1b1d5b

so it become a pain to code that way

if i reload unity without sudo, i cant add/change/delete any content i did before
so its not possible for me to use it in mac os.

**Comment by alvyxaz** [comment]
Hey!

Woah, that's strange.

What exactly do you mean by the "in monobehaviour some stuff dont load correctly"? I can't see what's wrong with the picture

If you start unity without sudo, you won't be able to run a server within editor (opening socket connections on Mac OS requires elevated permisions)

From the information provided, it seems like there's something wrong with Unity on Mac OS in general. Or I might have misunderstood something :)

**Comment by delmarle** [comment]
in the picture the text in red mean, not found or not loaded
if i re open the project with unity and not doing a sudo i cant modify any file that i created with the unity under sudo so project cant be shared over github for example

**Comment by delmarle** [comment]
im checking on internet for the error without using sudo, on this post they say to use port >1024 so i changed port 90 but it freeze unity for now when i start. simply get rid of the mac os problem would help a lot

http://mono.1490590.n4.nabble.com/Access-Denied-in-Socket-constructor-td1497458.html

**Comment by alvyxaz** [comment]
Oh, yeah, the >1024 port issue. I should probably make the default port to something higher than 1024. 

It's a bit hard for me to test things on MacOS, because I need to run it on a VM which is very slow.

So it still freezes on mac when you use a port higher than 1024 without sudo?

**Comment by delmarle** [comment]
yes, im still searching for solution with this

**Comment by delmarle** [comment]
if i use sudo and change port to anything different than 90 the connected status stay orange instead of green

**Comment by alvyxaz** [comment]
Alright, I'll try to look into it too.

By the way, I think you should report the sudo / MonoBehaviour / File editing issue to Unity (if it's replicated on an empty project).

**Comment by alvyxaz** [comment]
If it stays orange, it might be because client still tries to connect to port 90. Make sure it's changed on clients connection (connector) too. In the hierarchy, it's Barebones> Connection > MasterServerConnector

**Comment by delmarle** [comment]
yes i changed port everywhere to 1111 while using sudo now its green, but without sudo its still same socket error:

i have found someone with same problem using : 

void Connect()
{
//before connecting I need to tell unity to turn security off for the port im going to use
Security.PrefetchSocketPolicy(IP,PORT);
//now I can connect to the server with out any problems hopefully
ClientSocket.Connect(IP,PORT);
}

**Comment by alvyxaz** [comment]
I didn't know about the **PrefetchSocketPolicy**. Would you mind trying to add it in the Awake method of any script?

It will take me some time to setup the VM for Mac before I can try this

**Comment by delmarle** [comment]
i changed ServerSocketWs.cs

`public void Listen(int port)
		{
			Security.PrefetchSocketPolicy ("127.0.0.1", port);
            _server = new WebSocketServer(port);
            SetupService(_server);

            _server.Start();
            BmUpdateRunner.Instance.Add(this);
        }`

but without sudo its same error, if you need me to help you on this easily you can add me to skype:

delmarle.damien

**Comment by alvyxaz** [comment]
Hey!

Alright, so I've set up a VM with OS X El Capitan, which has a fresh Unity installation

* I've opened unity without sudo (normally)
* Created a new Unity project
* Installed the framework asset
* Opened **DemoMain** scene
* Changed port in hierarchy Barebones > Master Server >Client Port to **1500**
* Changed port in hierarchy Barebones > Connection > Port to **1500**
* Hit the editor "Play" button, and everything seems to be working fine

I also made a build for client, and used it to connect to the master server running on editor, and it also worked like it's supposed to.

From what I've gathered, Tatien (he has replied to one of your posts) is also running the framework on Mac OS without any problems

**Comment by delmarle** [comment]
Hey i just tested and it work perfectly with the following changes !
so happy you figured out a solution, i was about to purchase a windows pc to use your asset. big thanks!

**Comment by alvyxaz** [comment]
Awesome, great to hear that it's working! Have fun ;)

**Comment by delmarle** [comment]
it would be a good idea to update the docs here: https://github.com/alvyxaz/barebones-masterserver/wiki/Mac-OS-Ceveats

and update the default port to avoid this in next version because the project created with sudo dont allow mac users to export to edit/export scripts created, i can only copy paste the code i wrote by hand

**Comment by alvyxaz** [comment]
Thanks for reminding me about this! I've made the changes, and I'll change the default port on the next release ;)
