### ISSUE TITLE
How does Peer ID work?

### ISSUE THREAD

**Issue by tatien** [alvyxaz/barebones-masterserver#110]
Hi guys, 😃 

I'm trying to understand how works the peer ID, and I got some questions :

- How is set the ID ?
- If a game client crash did the peer id change when he reconnect ?
- If a player left can another player have the same id than the player who just disconnected ?

**Comment by alvyxaz** [comment]
Hey! ;)

PeerID is an integer, assigned to a connection, so every time you reconnect - you get a new peerID, and all the state of that peer is cleared (from perspective of a server).

When a client connects to server, he gets a new unique ID by something similar to `peerId = lastId++`, so a different player cannot have the same id. Id collision is impossible, unless a number of connections overflows Int32 value, which is pretty much impossible ;)

**Comment by tatien** [comment]
Thanks for the answers ! 😃
