### ISSUE TITLE
Connected To Master Server in Linux Vps, But GameServer Doesn't Work

### ISSUE THREAD

**Issue by fgurel** [alvyxaz/barebones-masterserver#159]
Hi,

I am receiving the same error as https://github.com/alvyxaz/barebones-masterserver/issues/13 with version v2.x.  I give the ip adress of my server, use port 5000 for Client, GameServer and MasterAndSpawner scenes' ConnectionToMaster. I also change the default exe path to ./GameServer.x86_64 in Spawner object in MasterAndSpawner scene. Yet I obtain the same screenshot, it still says connecting to 127.0.0.1:5000. Having received this I also fixed the ServerIp to my ip adress within ConnectionToMaster script yet still nothing changes. Using -bmpIp too does not change anything at all. Result is, client connects to master, yet after a succesful room creation game returns back to Game Creation menu scene with error

ClientDisconnected due to error: Timeout
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate()

Can anyone help?
Thank you,

PS: I have also written this under https://github.com/alvyxaz/barebones-masterserver/issues/13 as well, but since it's closed already wanted to open a new issue as well.

**Comment by fgurel** [comment]
![capture](https://user-images.githubusercontent.com/19366446/34829507-f91f2a18-f6f1-11e7-84df-b94c77a84f80.PNG)

This is the screenshot, right before it returns to GameList and then gives a Timeout error.
![capture2](https://user-images.githubusercontent.com/19366446/34829612-510884a4-f6f2-11e7-96af-934ade40f580.PNG)

**Comment by JoaoBorks** [comment]
I can see your **MasterAndSpawner** is on the linux VPS, but I guess the issue is, the **Master Server** and **Spawner** are on the same scene, so its **ConnectionToMaster** object should have the localhost address, otherwise the spawner will not be able to spawn Game Server instances because it will not be able to connect to the **Master Server**. However you should try some [command line arguments](https://github.com/alvyxaz/barebones-masterserver/wiki/Command-Line-Arguments) on the **MasterAndSpawner** app like -msfMachineIp

**Comment by fgurel** [comment]
Hello again,

Thank you for your answer. Do you mean the default machine ip in Spawner object? I used that as 127.0.0.1 but when it didn't work I tried my public ip to see it that would change anything but both of them have failed.

Also I start Master in the vps with `nohup ./MasterAndSpawner.x86_64 -msfStartMaster -msfMasterIp 176.31.24.102 -logfile &` and start the Spawener with `nohup ./MasterAndSpawner.x86_64 -msfStartSpawner -logfile &` where I have also tried to included "-bmIp 176.31.24.10"2 to both of them as suggested in https://github.com/alvyxaz/barebones-masterserver/issues/13 but that did not change anything as well.

**Comment by fgurel** [comment]
Also when all that have failed, I also changed UnetGameRoom's public ip for SimplePlatform scene from 127.0.0.1 to the vps' public ip to see some changed but not luck there too. 

![capture](https://user-images.githubusercontent.com/19366446/34832990-6cae510e-f6ff-11e7-9ba2-12102c292dce.PNG)

For this scene ConnectionToMaster is the same with others with the server's public ip.

**Comment by shubhank008** [comment]
Can you uncheck the "batch mode" option in MasterServer/Spawner to run the GameServer build with GUI and make sure its loading fully (I mean the specific scene its meant to load).  

I was having this kind of similar problem too where I was stuck on [ConnectionToMaster] Connecting to 127.0.0.1:5000 but wouldn't get the normal "scene initialized" message.  
I turned off the batchmode and realized that my gameserver's build was hanging up and crashing while trying to load the scene (even though same scene was working in my client build).  

I couldn't really figure out the real exact problem, but I tinkered around in my actual scene turning off a few things and stuff and figured out that in my case my player spawnpoint's position was for some reason causing it and after fixing it, I was able to run my GameServer.  

What I am saying is, the cause for you might be different but perhaps its possible that your GameServer is also not actually running up (upto the scene loaded/initialized state).  

PS: When running on server, I always now first try to run my build with GUI (non-batch) and if it works, then with batch mode

**Comment by matheus-crivellari** [comment]
I got an "aborted" message as the tutorial said. Analysing the log files on Linux I got the following message:

"Terminated game server because first player didn't show up."

Does someone knows what that mean or how to fix it?

**Comment by fgurel** [comment]
Thank you shubhank008 for your answer, I haven't had time to look into it for a while but I'll try it with non-batch mode and see if it works.

**Comment by fgurel** [comment]
Hello again,

The issue still continues with headless mode no matter what I try, and when I do not build GameServer headless and then upload it on the server, I receive the error "Game Creation Aborted" with no log files.

![fail](https://user-images.githubusercontent.com/19366446/35766835-a107fb8c-08f0-11e8-8551-c809e211beec.PNG)

**Comment by fgurel** [comment]
Hello again,

For anyone who is struggling with the same issue, I  re-installed unity,using 5.5.0 now, then followed every step in https://github.com/alvyxaz/barebones-masterserver/wiki/Tutorial:-Building-to-Linux-VPS again and this time got it working.

Don't know what was the issue but it is solved now.
