### ISSUE TITLE
How are you creating the actual GUI windows from the prefabs?

### ISSUE THREAD

**Issue by jeff-odg** [alvyxaz/barebones-masterserver#16]
I am looking at the MainEmpty scene and I see the scripts which are controlling the contents, however after looking through the scripts, I don't see any OnGUI functions to display things like the Lobby or the CreateGame windows within the scene.  

Is there a master script that is controlling the scene that I am just not seeing?

Let me know if the question makes any sense..

Thanks,

Jeff

**Comment by alvyxaz** [comment]
Hey!

Check out the Canvas object in the hierarchy - it's a part of new (relatively) Unity's UI system, and all of the UI components lay there.

These tutorials have more info:
https://unity3d.com/learn/tutorials/topics/user-interface-ui

If you didn't know that it exists, you're in for a suprise, haha

**Comment by jeff-odg** [comment]
Oh I knew the UI components were there.. my game is very UI dependent! What I didn't know was about the modal windows!! Not sure how I missed that.  I am on the steep learning curve that is Unity.. I will be proficient someday! 

Jeff

**Comment by alvyxaz** [comment]
Haha, good luck on your quest! ;)
