### ISSUE TITLE
Client able to join at room even after a started match

### ISSUE THREAD

**Issue by MsbowElite** [alvyxaz/barebones-masterserver#161]
How to hide the room after the host click on the startButton?

I am trying to place this code 
`Msf.Server.Rooms.GetRoomController(access.RoomId).MakePrivate();`
But the client have a null exception on Rooms, obviously.

I just realized the master user of the lobby will have the room id at starting stage of a game server on this method:

> TriggerAccessReceivedEvent

**access.RoomId**

then i added a method on RoomController
MakePrivate instead of MakePublic.

Anyone can figure out the best way to hide a room from gameList after a started stage?

**Comment by fgurel** [comment]
Hello,
I see that you have deleted the question but did you have any luck with the issue? I am trying to do something similar, so I was wondering if you solved the issue or not; and if so how did you achieve it?
Thanks,
