### ISSUE TITLE
[Question] How To Access Lobby Properties From Game Server

### ISSUE THREAD

**Issue by ArneSaknussemm89** [alvyxaz/barebones-masterserver#165]
Been playing around with this for a couple of weeks and am slowly starting to wrap my brain around how everything works (primarily trying to understand how the supplied Lobby/Room modules work)

I just wanted to add a small script to the client scene to get the lobby properties (teams, props set in the factory, etc etc) but I’m a little lost as to how would I do that as I don’t see the Lobby props being passed to the Room registration and in the UnetGameRoom I didn’t see those values on the RoomController. 

Any direction here would be fabulous.

**Comment by ArneSaknussemm89** [comment]
In case anybody sees this and goes "Me too!", I was able to figure it out.

Using the `Msf` object you can call some default operations provided by the Lobbies/Rooms modules.

Here is a snippet showing how I was able to grab Lobby property data when the Client Scene is loaded (I placed this inside `UnetGameRoom.cs` around line 316 inside the HandleReceivedAccess function):
```
if (Msf.Args.IsProvided(Msf.Args.Names.LobbyId))
{
  Msf.Server.Lobbies.GetMemberData(Msf.Args.LobbyId, validatedAccess.PeerId, (memberData, errorMessage) => 
  {
    if (memberData == null) {
      Logger.Debug(errorMessage);
      return;
    }

    Logger.Debug(string.Format("This Peer is on the {0} team", memberData.Team));
  });
}
```

You can get the entire LobbyData by using `Msf.Server.Lobbies.GetLobbyInfo` and passing that the LobbyId (which was be easily retrieved by using `Msf.Args.LobbyId`. That value is a command line argument passed to the application by the spawner).

**Comment by ghost** [comment]
You should close this issue if you solved it :)
