### ISSUE TITLE
Launch the demo on Mac OS

### ISSUE THREAD

**Issue by tatien** [alvyxaz/barebones-masterserver#2]
Hi,

I'm trying to launch the demo from my editor on mac os but I get an error SocketException: Access denied. 

<img width="1280" alt="screen" src="https://cloud.githubusercontent.com/assets/16664220/19382867/491036e4-9202-11e6-9780-ad278a72bb08.png">

Do you have any idea ? Maybe compatibility issue with MacOS ?

**Comment by alvyxaz** [comment]
Hey,

That's strange. It should work on MacOS, especially the networking part (sockets), as it's nothing fancy. 

I'm not an experienced MacOS user, but my guess is that editor doesn't have permission to open sockets. You'll probably need to run the editor in **sudo**.

Let me know if this resolves the issue :)

**Comment by tatien** [comment]
Thanks, the `SocketException: Access denied` can be solve by `sudo   /Applications/Unity/Unity.app/Contents/MacOS/Unity` .

But I get another error : Make sure that your Spawner Server has a correct path to your build
<img width="1280" alt="screen2" src="https://cloud.githubusercontent.com/assets/16664220/19388044/ee9da87e-921d-11e6-8b75-584a734d8e9f.png">

> System.ComponentModel.Win32Exception: ApplicationName='/Users/Tatien/Documents/Build/Test.app', CommandLine=' -bmStartUserCreated -bmFps 30 -bmInstanceId 1652 -bmMasterKey "" -bmGamePort 1000 -bmIp 127.0.0.1 -bmMasterIp 127.0.0.1 -bmGamesPort 5001 -bmScene "GameRoom" ', CurrentDirectory=''
  at System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
  at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x00000] in <filename unknown>:0 
  at Barebones.MasterServer.SpawnerServer+<SpawnServer>c__AnonStorey57.<>m__7C () [0x0001b] in /Users/Tatien/Documents/Jeux/Base Defence/Master Server Framework Test/Assets/Barebones/MasterModules/SpawnerServer/Scripts/SpawnerServer.cs:350 
UnityEngine.Debug:LogError(Object)
Barebones.MasterServer.<SpawnServer>c__AnonStorey57:<>m__7C() (at Assets/Barebones/MasterModules/SpawnerServer/Scripts/SpawnerServer.cs:376)

I check the path and the app is here.

**Comment by alvyxaz** [comment]
Try opening the `Barebones/MasterModules/SpawnerServer/Scripts` **/SpawnerServer.cs**.

Locate `void SpawnServer` method, line  322, where it says:

`UseShellExecute = false`

and try to change it to `true`

**Comment by tatien** [comment]
I try with UseShellExecute = true, but it is still not working. 
<img width="1280" alt="screen3" src="https://cloud.githubusercontent.com/assets/16664220/19410602/873f24c2-92f0-11e6-9c8a-b007850d0159.png">

> Spawn task aborted: Game closed
UnityEngine.Debug:LogWarning(Object)
Barebones.MasterServer.SpawnTask:Abort(String) (at Assets/Barebones/MasterModules/SpawnerServer/Scripts/SpawnTask.cs:186)
Barebones.MasterServer.SpawnersModule:OnGameServerClosed(Int32) (at Assets/Barebones/MasterModules/SpawnerServer/Scripts/SpawnersModule.cs:371)
Barebones.MasterServer.SpawnersModule:<Initialize>m__80(IIncommingMessage) (at Assets/Barebones/MasterModules/SpawnerServer/Scripts/SpawnersModule.cs:102)
Barebones.Networking.PacketHandler:Handle(IIncommingMessage) (at Assets/Barebones/Networking/Scripts/PacketHandler.cs:26)
Barebones.MasterServer.SpawnersModule:HandleMessage(IIncommingMessage) (at Assets/Barebones/MasterModules/SpawnerServer/Scripts/SpawnersModule.cs:384)
Barebones.Networking.BasePeer:HandleMessage(IIncommingMessage) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:220)
Barebones.Networking.BasePeer:HandleDataReceived(Byte[], Int32) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:252)
Barebones.Networking.<SetupService>c__AnonStorey5E:<>m__94(Byte[]) (at Assets/Barebones/Networking/Scripts/ServerSocketWs.cs:70)
Barebones.Networking.WsService:Update() (at Assets/Barebones/Networking/Scripts/ServerSocketWs.cs:145)
Barebones.Networking.ServerSocketWs:Update() (at Assets/Barebones/Networking/Scripts/ServerSocketWs.cs:101)
Barebones.Networking.BmUpdateRunner:Update() (at Assets/Barebones/Networking/Scripts/BmUpdateRunner.cs:49)





> Received kill request:  1652
UnityEngine.Debug:LogWarning(Object)
Barebones.MasterServer.SpawnerServer:<Awake>m__7A(IIncommingMessage) (at Assets/Barebones/MasterModules/SpawnerServer/Scripts/SpawnerServer.cs:109)
Barebones.Networking.PacketHandler:Handle(IIncommingMessage) (at Assets/Barebones/Networking/Scripts/PacketHandler.cs:26)
Barebones.Networking.ClientSocketWs:HandleMessage(IIncommingMessage) (at Assets/Barebones/Networking/Scripts/ClientSocketWs.cs:249)
Barebones.Networking.BasePeer:HandleMessage(IIncommingMessage) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:220)
Barebones.Networking.BasePeer:HandleDataReceived(Byte[], Int32) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:252)
Barebones.Networking.ClientSocketWs:Update() (at Assets/Barebones/Networking/Scripts/ClientSocketWs.cs:116)
Barebones.Networking.BmUpdateRunner:Update() (at Assets/Barebones/Networking/Scripts/BmUpdateRunner.cs:49)

**Comment by alvyxaz** [comment]
Alright, so it seems that spawner successfully found the path to executable. Just to make sure, do you see a "game server" window pop up? If it does, how long does it take for it to close itself?

Check out the **Enable Builds To Run In Background**:
https://github.com/alvyxaz/barebones-masterserver/wiki/Important-Stuff

One of the reasons why game servers close automatically is that no players connect to it. If **Run In Background** is not selected, either game server or client will stop executing code when one of the windows is inactive, thus not allowing for client to connect.

**Comment by tatien** [comment]
The run in background setting is enable but no game server pop up.

**Comment by alvyxaz** [comment]
I'll setup a virtual Mac OS machine and try to replicate the issue.

Once I resolve it, I'll get back to you.

I'm really sorry for all the trouble this is causing. Before the release, I had a copy sent to Mac tester, and he didn't report any issues. I'm guessing he didn't really try it :/

**Comment by tatien** [comment]
I also try without the editor:
`sudo ./Build.app/Contents/MacOS/Build -bmMaster -bmSpawner`

And I get the same issue.

**Comment by alvyxaz** [comment]
I was going to suggest running the master server from build, thanks for trying it yourself.

To clarify, when you run
`sudo ./Build.app/Contents/MacOS/Build -bmMaster -bmSpawner`

the master starts, right? 

Or did you mean that even the master server couldn't be started?

**Comment by tatien** [comment]
I think the master server start (left part of the screenshoot), I use `sudo ./Build.app/Contents/MacOS/Build -bmMaster -bmSpawner`. I try to start an game instance with `sudo ./Build.app/Contents/MacOS/Build` (right part of the screenshoot).
<img width="1279" alt="capture d ecran 2016-10-15 a 20 18 32" src="https://cloud.githubusercontent.com/assets/16664220/19412375/03865680-9315-11e6-93bb-2fa3c345f8e8.png">

**Comment by alvyxaz** [comment]
Oh, ok. So the main problem is just "spawning" a game server.

There's probably something special with how Mac OS handles process spawning in Mono environment (most likely resolving a path)

By the way, you should probably revert to`UseShellExecute = false,`.

I think I've read somewhere that build file's "execute permission" might not be set, but given that you run it from terminal without problems, I don't think it's the case.

PS. I almost have the VM set up. I'll get more answers when it's done

**Comment by alvyxaz** [comment]
By the way, I found a suggestion online saying that the build should be at `/Applications` folder, like:

`"/Applications/Inkscape.app/Contents/Resources/bin/inkscape"`

Could you try that out? With both `UseShellExecute = false` and `UseShellExecute = true`

**Comment by tatien** [comment]
I tried with both, with false I got the same error than in my third post and with true same error than in my last post.

**Comment by alvyxaz** [comment]
I've set up the virtual machine, and managed to launch an empty Mono executable from within another.

I'll try to do that with Unity tomorrow morning

**Comment by alvyxaz** [comment]
Hey,

I've managed to get servers spawned on Mac OS X El Capitan virtual machine.

Seems like the main problem was indeed related to Path to executable resolving.

I  run this command to start the master server:

`sudo /Users/admin/Documents/Build.app/Contents/MacOS/Build -bmMaster -bmSpawner -bmExe "/Users/admin/Documents/Build.app/Contents/MacOS/Build"`

Note the additional parameter `-bmExe`, which overrides the path to game server executable.

I'm now working on improving the default path resolving, and I'll send you a patch once it's done. 

I did not yet try installing Unity and starting servers from within the editor on my virtual machine - it's crazy slow, but I'll get it installed soon.

**Comment by tatien** [comment]
Yes it work :), thanks for your support.

<img width="1280" alt="capture d ecran 2016-10-16 a 11 43 15" src="https://cloud.githubusercontent.com/assets/16664220/19416680/67946018-9397-11e6-960f-98db6dfe8907.png">

**Comment by alvyxaz** [comment]
Really great to hear that! Once again, sorry for all the inconveniences :/

**I have one more question if you don't mind:**

At first, you've mentioned that when you started master server in editor, it wouldn't spawn game servers. At that point, you had the path like this:

`/Users/Tatien/Documents/Build/Test.app`

Could you try extending it to this (or similar):

`/Users/Tatien/Documents/Build/Test.app/MacOS/Build`

And see if servers can be started from master server which is running in the editor? Editor on my VM freezes and I can't test it, haha

**Comment by tatien** [comment]
I tried but it doesn't start any game server.

**Comment by alvyxaz** [comment]
Alright, so I'll be investigating this further and inform you about the progress

**Comment by alvyxaz** [comment]
I've finally managed to get Unity editor running on the VM. I've downloaded the asset, and without making any changes, I got everything to work (running master server from both editor and from a build).

I've also created a new page in documentation, where I wrote what I had to do to run the demo:
https://github.com/alvyxaz/barebones-masterserver/wiki/Mac-OS-Ceveats

**Comment by tatien** [comment]
I re-import everything and it's look good. 
Thank you !!
