### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tophermade** [alvyxaz/barebones-masterserver#20]
It would be fantastic to get a change log when a new version hits the asset store. I saw a new update go live, but without a log I don't know if it's worth taking the time to upgrade and test or not - change log would solve that for everyone.

**Comment by alvyxaz** [comment]
Before the release, I've added an "Updates" page to the documentation. I guess it would be more appropriate to call it changelog, haha

https://github.com/alvyxaz/barebones-masterserver/wiki/Updates

**Comment by tophermade** [comment]
Awesome I didn't know about that page, thanks!
