### ISSUE TITLE
Can't show list of created lobby

### ISSUE THREAD

**Issue by smuggler20** [alvyxaz/barebones-masterserver#22]
Hi,
I have such a problem that i can't show list of created lobby. When I create a lobby and play it alone from one client, everything is ok, but when first client create a lobby and second client try refresh list of games, I get this error: 
![error](https://cloud.githubusercontent.com/assets/9079582/21681557/ffb88124-d34f-11e6-9f78-6bc79f7d2dfa.jpg)
If it helps, I check that I get null here:
![error2](https://cloud.githubusercontent.com/assets/9079582/21681676/85a5f3d4-d350-11e6-9c1d-7fffc36fb6ec.jpg)
Do you know why this happens and what I'm doing wrong?

**Comment by alvyxaz** [comment]
Hey!

I probably forgot to make sure that Address value is never null. (Address is know only after the game is actually started)

For a quick fix, try this:

![image](https://cloud.githubusercontent.com/assets/3227731/21681928/3cd12f2a-d35a-11e6-9bd4-7a0ea23eb5f9.png)

**Comment by smuggler20** [comment]
Thank you very much, it works!

**Comment by alvyxaz** [comment]
Fixed in V1.03.1
