### ISSUE TITLE
Master Server Framework errors on import with Unity 5.5.0

### ISSUE THREAD

**Issue by fgurel** [alvyxaz/barebones-masterserver#23]
We have downloaded and imported Master Server Framework to our Unity 5.5.0 project, however we have received following errors. What seems to be the issue here? Thank you,

Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(31,37): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnServerAddPlayer(UnityEngine.Networking.NetworkConnection, short)' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(37,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnStartServer()' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(43,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnStopClient()' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(51,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnClientConnect(UnityEngine.Networking.NetworkConnection)' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(60,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnClientDisconnect(UnityEngine.Networking.NetworkConnection)' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(74,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnServerConnect(UnityEngine.Networking.NetworkConnection)' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(89,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnServerDisconnect(UnityEngine.Networking.NetworkConnection)' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(98,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnStopServer()' is marked as an override but no suitable method found to override
Assets/Barebones/MasterModules/Games/Scripts/Unet/EventfulNetworkManager.cs(104,30): error CS0115: `Barebones.MasterServer.EventfulNetworkManager.OnStartHost()' is marked as an override but no suitable method found to override
Assets/Barebones/Demos/MiniGame/Scripts/MiniNetworkManager.cs(9,26): error CS0115: `MiniNetworkManager.OnServerAddPlayer(UnityEngine.Networking.NetworkConnection, short)' is marked as an override but no suitable method found to override

**Comment by fgurel** [comment]
Turns out that changing NetworkBehaviour to NetworkManager prevents the errors. I'm not sure if it is correct though.

**Comment by alvyxaz** [comment]
Hey!

It's correct. I have no idea why it would have imported as a
NetworkBehaviour.

I'll check it out when I get back, but I'm pretty sure it should not have
happened. I've tried downloading it yesterday and it was working fine.

Stranger things have happened, though :)

**Comment by alvyxaz** [comment]
Yup, I've just tried importing the asset from the store, and the error did not appear (`EventfulNetworkManager` extends `NetworkManager`).

Quite strange. Let me know if this behaviour repeats, and for now I'll close the issue ;)

Thanks for reporting!

**Comment by fgurel** [comment]
I don't know why it happened either, but I'll let you know if it repeats.
Thank you for the quick reply!
Regards,
Gurel

**Comment by Paradoks-Studio** [comment]
Hi guys, 

I am getting this error too, but, when i import the tank network demo from the asset store and then import the master Server asset, i dont get the errors, wich would mean that it is not 5.5 involved.
I realised too that i had a script called SceneManager wich is the name of a unity class:
https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html

Is it a conflict ? I replaced my sceneManager by a MasterSceneManager, i dont get the bugs anymore, but somehow i cant launch the game anymore....

fgurel, did you find a workaround ?

**Comment by alvyxaz** [comment]
SceneManager has been around before 5.4, and I don't think it should cause conflicts, because all of the unity scripts are under UnityEngine.* namespace.

As fgurel has mentioned, he replaced `NetworkBehaviour ` to `NetworkManager` in `EventfulNetworkManager `.

My guess is that Unity's internal "upgrade" functionality falsely changes NetworkManager into NetworkBehaviour (I'm not sure on which occasions)

**Comment by fgurel** [comment]
Hello again,

As alvyxaz mentioned I replaced  NetworkBehaviour to NetworkManager in EventfulNetworkManager which solved my issue.

I just wanted to mention one more thing which is I only got this error for a project that I have upgraded from Unity 4.x to Unity 5. Now when I create new projects with Unity 5 and import Master Server Framework I don't get this error.  

Hope it helps,
Gurel
