### ISSUE TITLE
Is this legit?

### ISSUE THREAD

**Issue by MichaelAtHotkey** [alvyxaz/barebones-masterserver#235]
On the Unity Asset Store page for this asset, there is a review from a user named Aevien saying:

> Asset is not abandoned! It's alive!
> 5 months ago
> New releases:
> 
> 3.8.+
> 
> https://master-toolkit.com/

After checking the link and going to its repo, its a different github user and appears to be a completely different code base. The user for the repo is actually the same person that made the review mentioned above.

Is that repo actually the successor to this repo or is it unrelated to this one?

**Comment by thatjoaoguy** [comment]
That is a [fork](https://github.com/aevien/master-server-framework) of this repository that is maintained by someone else. I have not tested but looks like it's receiving recent updates.

**Comment by MostHated** [comment]
It has been quite active the last few months and seems to be pretty well received.
