### ISSUE TITLE
Question:  Is there documentation on creating a Game Server and tying them into the Spawner Server/Master Server?

### ISSUE THREAD

**Issue by jeff-odg** [alvyxaz/barebones-masterserver#24]
I love the new Build From Scratch docs you put up. It has helped this new user immensely. However the issue I have is I have a game set up in a project and I want to spawn a server per table/game.  I am having trouble with the existing docs not seeming to have coverage on the game server itself.

Am I just missing it?
If not, is there some on the way?

Keep up the amazing work!

J.

**Comment by alvyxaz** [comment]
Hey!

Regarding the integration into an existing game, this might be of some use:
https://github.com/alvyxaz/barebones-masterserver/wiki/Getting-Started

With the "From Scratch" series, I'm making my way to writing more details
about how game servers work. I think it should be done in the next few days
;)
