### ISSUE TITLE
Q: Facility for returning to an existing lobby?

### ISSUE THREAD

**Issue by tophermade** [alvyxaz/barebones-masterserver#25]
I'm building off your excellent lobby setup, and I can't tell if there is functionality already implemented for returning to the lobby, say at the end of a round. And if not can one retrieve the lobby the player was in previous to the map load?

**Comment by alvyxaz** [comment]
Hey!

Currently, in demo, when a player exits the game, he should automatically see the Lobby window.

The way it works is:

1. Player returns to main screen 
2. `MainScreen.cs` checks if player is currently in a lobby (if server considers player as being in a lobby) 
3. If player is in lobby, it shows the lobby window (`MainScreen.ShowLobbyIfInLobby` method)

So to answer the question if player can retrieve the lobby - yes. By default, when client leaves a game, he doesn't leave the lobby. `LobbiesModule.IsInLobby` method can check if user is in lobby. If he is LobbyView component (on lobby window/ui) can be enabled, and it should retrieve all the data of the current state of the lobby.

Let me know if this answer is of any help :)

**Comment by tophermade** [comment]
Fantastic, thank you.
