### ISSUE TITLE
[QUESTION]Where is data stored in LiteDB?

### ISSUE THREAD

**Issue by xgcell** [alvyxaz/barebones-masterserver#27]
I would like to know where my data is stored in LiteDB.  On their page, it said that it is stored in a Bson document.  I cannot find this.  I have created an account on the mainDemo scene, and I know the data is being stored someplace, I just cannot find it in the source.

I am trying to decide if I want to keep LiteDB or throw it away.  I already have a MySQL file dump of my database containing about 40 tables, and ranging between 5 to 50 columns each. I also need a website to be able to access the database, should I bother with LiteDB?

**Comment by alvyxaz** [comment]
If you're going to access your data on a website, it's probably better to use MySQL or other well established database solution. LiteDB is good for  making prototypes quickly, but it's far from perfect when you want to do more things with the data.

To answer the question, when you run the master server, database files are created at the same folder as the executable, and they are called:

- `auth.db`
- `profiles.db`

**Comment by xgcell** [comment]
Ahh that's where they are! I figured that they would be listed in visual studio solution files.  
For those that this may help, you need another tool to read the database files such as: www.github.com/mbdavid/LiteDB/releases
