### ISSUE TITLE
FromScratch - Client Username

### ISSUE THREAD

**Issue by dbladez** [alvyxaz/barebones-masterserver#28]
I'm currently working through the FromScratch introduction to get up to speed on how the master server / client work together and I've come across an odd issue.

In [this](https://github.com/alvyxaz/barebones-masterserver/wiki/From-Scratch.-Adding-Authentication#client) part there is a portion of code that logs the user in as a guest and sets the usernames text field to the ID that has been assigned to them but it seems like my label isn't being populated. 

Stepping through the function it appears to be setting it correctly as you can see 
![here](https://cloud.githubusercontent.com/assets/8118216/22135368/c8f37886-de9b-11e6-806a-076c2cb45043.png) but when the canvas renders the username it appears as 
![this](https://cloud.githubusercontent.com/assets/8118216/22135398/e0a730f8-de9b-11e6-880f-a9f1751daebc.png). 

Any idea what is going on?

**Comment by alvyxaz** [comment]
Hey!

My guess is that width of text object/component is too small to fit in the username. By default, when content doesn't fit, it's hidden. If that's the case, try changing overflow settings to these:

![image](https://cloud.githubusercontent.com/assets/3227731/22142600/8fb0977a-deff-11e6-9cf4-b1695271f823.png)

**Comment by dbladez** [comment]
Oh, wow, I feel dumb! I guess I should stop working in Unity before going to bed, haha. That's all it was. I completely forgot the labels in Unity don't scale to the content by default. I'm going to close this as it's a non-issue.

**Comment by alvyxaz** [comment]
Haha, it happened to me more times than I'd want to admin 😄
