### ISSUE TITLE
Start Master Server

### ISSUE THREAD

**Issue by CortexM4** [alvyxaz/barebones-masterserver#32]
Hi all.
I'm try to start a master server after click on my button.

> Alternative: Create a new script that will find Master in the scene, and call the master.StartServer() whenever you want (click of a button and so on)

I'm using singleton
`Master.Instance.StartServer();`

and receiving this error

> NullReferenceException: Object reference not set to an instance of an object
> StartServerScript.OnStartServerClick () (at Assets/FromScratch/Scripts/StartServerScript.cs:8)

This's occur because _clientsSocket is NULL in `public virtual void StartServer()` in Master.cs

OK, I've seen that code `_clientsSocket = Connections.CreateServerSocket();` not executed
because in Awake method (Master.cs) condition
```
if (ShouldBeDestroyed())
{
        Destroy(gameObject);
         return;
}
```
always TRUE

It's occur in Editor and in executable file. Flag `Auto Start In Editor` I'm disabled.
After comment
```
Destroy(gameObject); 
return;
```
It's work fine.

PS:
Sorry for my English. :)

**Comment by alvyxaz** [comment]
Hey!

Thanks for catching and reporting this!

I'll make sure it's fixed in the next update ;)
