### ISSUE TITLE
Getting Errors When Following The Tutorial

### ISSUE THREAD

**Issue by fgurel** [alvyxaz/barebones-masterserver#33]
Hello,

I have been following the from scratch tutorial, I have completed the first 4 but with the authentication step I have started receiving errors.

The first one is when I use "Log in as guest" button, even though the client is seen as connected to master, I  get "Error: Internal Server" error. 

Then when I try to Get Games, I get the following:
Requesting a list of games
UnityEngine.Debug:Log(Object)
Server did not handle the request properly
UnityEngine.Debug:LogError(Object)
GamesRequester:<RequestGames>m__0(Byte, IIncommingMessage) (at Assets/Scripts/GamesRequester.cs:36)
Barebones.Networking.BasePeer:TriggerAck(Int32, Byte, IIncommingMessage) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:208)
Barebones.Networking.BasePeer:HandleDataReceived(Byte[], Int32) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:235)
Barebones.Networking.ClientSocketWs:Update() (at Assets/Barebones/Networking/Scripts/ClientSocketWs.cs:148)
Barebones.Networking.BmUpdateRunner:Update() (at Assets/Barebones/Networking/Scripts/BmUpdateRunner.cs:53)

I guess the problem is with the server side, though I'm not sure what to do. 
Thank you,
Regards Gurel

**Comment by alvyxaz** [comment]
Hey!

Could you try changing the line at `RequestGames()` which prints the error to this:

``` C#
Debug.LogError("Server did not handle the request properly: " + status);
```

This should tell us what kind of an error you're getting, and it might be a similar problem as with the Login

**Comment by fgurel** [comment]
Hello again,

With status added I have the following:

Server did not handle the request properly: 3
UnityEngine.Debug:LogError(Object)

**Comment by alvyxaz** [comment]
Master server doesn't show any errors?

Try to open the `LoginUserHandler.cs` file, and debug or ad some logging to the `Handle` method, to see if it gets called and where it stops.

**Comment by fgurel** [comment]
I am running the master.exe on a windows machine. HUD shows that Master Server is active under 'Servers Running'. I didn't receive any errors when running it from cmd as well with the given -bmMaster argument.

Also I have added a Debug message at the beginning of the Handle method as you suggested and it turns out that it's not called.

**Comment by alvyxaz** [comment]
Are you sure you've made a development build, and logged the message as Error? (otherwise errors don't appear when running at .exe)

If you don't mind, add the master project to a zip, and publish somewhere or send me to alvyxaz@gmail.com, and I'll check it out :)

**Comment by fgurel** [comment]
I am not so good with Unity so I'm not really sure if I've made a development build or not.  I've just built it like in the tutorial so I don't know.

I'll send it right away. Thank you so much!

**Comment by alvyxaz** [comment]
No problem!

I just tried running master from both, editor and from a build, and it seems to be working.

Send me over a client too, maybe it's what's broken :/

**Comment by alvyxaz** [comment]
I tried using your client to log in to your master server, and **it's working** - I have no idea why it's not working on your machine.

Are you running it on Windows?

And did you try running both client and server in the editor (on separate unity editor instances)?

**Comment by fgurel** [comment]
Yes I'm running it on Windows, maybe that is not the best idea.
Also running both of them in separate editor instances seems to solve the issues. Why would this happen?

**Comment by alvyxaz** [comment]
Windows should be great - I'm always using it on windows, except for when I want to host it.

It's hard to tell. It's possible and most likely that you made a build earlier, and then didn't update it when the authentication module was added. Or made a new build in a different place, but still used the old one to start a master server.

Or had a master server running from a previous tutorial, and your client was always connecting to the old one.

Also, check the **Enable Builds To Run On Background** just in case. It should no longer be an issue (as of V1.03, but you can never be certain)
https://github.com/alvyxaz/barebones-masterserver/wiki/Important-Stuff

**Comment by fgurel** [comment]
It was enabled to run in the background so that doesn't seem to be the problem, but anyway thank you very much for your support!
With Regards,
Gurel
