### ISSUE TITLE
Issue using the GamesList prefab

### ISSUE THREAD

**Issue by EmilRainero** [alvyxaz/barebones-masterserver#36]
I completed the Getting Started pages on the wiki. 
I added a Games Server and tested if it works with a Get Games button. Console showed the correct information.

I added the GamesList prefab to the canvas.

1.  It was not visible - had to enable it in the inspector. You might want it to be defaulted to Active.

It now shows the list of game servers perfectly. Sorry to raise the other issue. It resolved itself.

**Comment by alvyxaz** [comment]
Thanks for notifying me about the inactive games list prefab! 

I'll have it default to active for the next update, and I'll close this issue after doing so ;)

**Comment by EmilRainero** [comment]
Of course. Glad to help. Really like the package.
I
