### ISSUE TITLE
Documentation issue in Getting Started Guide

### ISSUE THREAD

**Issue by EmilRainero** [alvyxaz/barebones-masterserver#38]
Original directions:
1.Add MasterServer to scene. This script will automatically start master server when you hit "play" button in the editor
2.Add GameServerStarter prefab to scene- it will automatically start your game server (after master server starts)
3.Add UnetConnector prefab to scene - it has a flag, called Auto Join If Host, which, as the name suggests, will try to automatically join the game, by first connecting to master and logging in.
4.Add Hud prefab to the Canvas object in the hierarchy. It will help you see if the servers were started successfully.

Two issues:
- MasterServer, GameServerStarter, UnetConnector should be added to Networking object.
- The Hud prefab is in the UI subdirectory.

Suggested change:
1.Add MasterServer to the Networking object. This script will automatically start master server when you hit "play" button in the editor
2.Add GameServerStarter prefab to the Networking object. It will automatically start your game server (after master server starts)
3.Add UnetConnector prefab to the Networking object. It has a flag, called Auto Join If Host, which, as the name suggests, will try to automatically join the game, by first connecting to master and logging in.
4.Add Hud prefab in the UI folder to the Canvas object in the hierarchy. It will help you see if the servers were started successfully.

PS
Hope you don't mind the documentation suggestions. A fresh set of eyes doing the exercises could help improve your product.
Do let me know if you prefer that I don't submit the documentation issues.

**Comment by alvyxaz** [comment]
Hey!

Thanks a lot for taking your time with this. It's not really necessary to add those scripts to the Networking object, but it makes does make things more clear.

And if you have any thoughts on how to improve the general setup, I would really like to hear them too. Even if it's a big change, I'd consider it, because I want to make the framework as easy to setup a s possible.

Thanks again!

**Comment by EmilRainero** [comment]
Glad to help.
Yes I understood about the scripts could be added to any of the objects, but for consistency sake and makes it exactly like getting started guide.

Your wiki is excellent. I have been looking for the documentation to include something like javadocs, but open the sources works well enough.

Your introduction to the framework was excellent. I am using Forge Networking Remastered and they really lack the big picture documentation.

It's too early to give you any other advise. Let me try moving a bit past your documentation and then maybe I will have additional feedback.
