### ISSUE TITLE
Trouble with SpawnerServer registration with Visual Studio debugging

### ISSUE THREAD

**Issue by EmilRainero** [alvyxaz/barebones-masterserver#40]
I added a SpawnerServer to the From Scratch server project and I get the following logging when running within Unity.
[Info] Spawners module started
[Info] Spawner Server Started : 127.0.0.1:5002
[Info] Master Server started
[Info] Spawner server connected. Peer id: 0
[Info] Spawner server connected to master
[Info] Spawner registered (True)

If I attach the Visual Studio debugger, I get
[Info] Spawners module started
[Info] Spawner Server Started : 127.0.0.1:5002
[Info] Master Server started

It never registers the Spawner Server. The best way to learn the software is with debugging and the behavior changes. Is there something I should set to allow debugging to not affect the networking behavior?

**Comment by alvyxaz** [comment]
Hey! This is an interesting behaviour.

I've just tried it on my machine, and it successfully went through all of the steps. 

However, while working on V1.04, I have a slightly modified version of startup-flow (I doubt it had any effect on what you've reported).

Would you mind waiting until the initial release of V1.04? (I should finish it in a couple of days). If this issue continues, I'll try to dig deeper.

**Comment by EmilRainero** [comment]
I can wait. No rush.
