### ISSUE TITLE
mongo db switch-over docs

### ISSUE THREAD

**Issue by pjbaron** [alvyxaz/barebones-masterserver#43]
First, _great_ news about 2.0 it sounds awesome and as we're only testing technologies right now I'll be switching to it as soon as it's ready :)

This is not an 'issue' but you suggested this is the best way to contact you in the wiki front-page.

Can we get some more details on how to switch over to MongoDB from the litedb solution?
I figured it might be as simple as just changing the MasterServer 'Database' object's script, but after doing that I get 'internal server error' when trying to login.

I'll keep trying to track it down (and update if I find the problem) but currently the database page mainly just talks about how it uses interfaces and factories, without any 'step-by-step' instructions for those of us with very little db experience.

cheers,
Pete

**Comment by pjbaron** [comment]
A little more detail about why this is needed.

I created an out-of-the-box webgl client using the "MyGame" scenes provided, and compiled it for webgl debug, then ran the unity version to get the servers going.  When I started the client in Firefox it generated this error:

The referenced script on this Behaviour (Game Object 'LiteDb') is missing!
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Mono/MonoBehaviour.cpp Line: 1754)

So it looks like litedb is [not supported in webgl](https://github.com/mbdavid/LiteDB/issues/448)

**Comment by alvyxaz** [comment]
Hey! I'll get back to you in a few hours with a full response

P.s. database code should not be running on clients :)

**Comment by pjbaron** [comment]
Oh, well that's weird lol [😊]  I look forward to your response!

cheers

Pete



________________________________

**Comment by alvyxaz** [comment]
Regarding the LiteDB, try changing the LiteDbFactory script to this:
https://gist.github.com/alvyxaz/ccc108bef619ab00ca561855e241b27a

And for the MongoDB, do you have it installed and running on your system :)?

By the way, what's the core functionality that you need from the framework?

The reason why I'm asking is because it's probably best to start working
with V2.0 as soon as possible. I finished the core networking
functionality, and finished game rooms module (game sever can now register
to it, and players can get permissions to access them). I'm planning to do
the spawner server functionality today, and user authentication tomorrow :)

**Comment by pjbaron** [comment]
I'll check those things first thing tomorrow (it's late here in New Zealand and I want to go do something else :) )


We're just starting on an asynchronous massively multiplayer game.  Something like Dungeon Boss / Summoner's War / Clash of Clans / Boom Beach etc

For this type of game, the networking will be relatively low pressure at the client side, potentially very heavy traffic on the server side with LOTS of clients connected to many game servers.

We'll also have an absolutely HUGE amount of database traffic, so LiteDB would just die.  I've read good things about MongoDB but if we run into problems there then I'll have to fall back to MySql which has been extremely reliable for games like Freefall Tournament [FFT] (a real-time first person shooter with lots of database actions and a few thousand players simultaneously).


One thing the FFT coders did which I might need to consider is they made a 'database connector' program, so instead of getting hundreds of queries from different IP addresses all at the same time, the game server queries the connector, and the connector feeds the requests to the database in a nice ordered queue.  I think this might be one reason why the database for that game has been running for 6 years and hasn't failed once (that I'm aware of - I've only been on the project for a couple of months) ;)


It sounds like v2.0 is going to be a big jump forwards and really make things a lot easier for the project, I'm currently stalling the bosses a bit because I'd like to see the API map for v2.0 before going too far on development with 1.03

Also sounds like you're making great progress - keep it up [😃]


cheers

Pete


________________________________
