### ISSUE TITLE
client server version check

### ISSUE THREAD

**Issue by skinnymeat** [alvyxaz/barebones-masterserver#44]
I an trying to make a check between the client and the server to make sure that they are the same version. I can't figure out where to best put that. Could you suggest where I would?

**Comment by alvyxaz** [comment]
Hey!

The best way to do this would probably be creating a new module, or using the existing one if you already created one for your game:
https://github.com/alvyxaz/barebones-masterserver/wiki/Creating-Modules

You would add a new message handler to that module, which would handle a request from user. User could send a message with a string of version, the handler would check if it's correct, and respond success/failure accordingly.

I'm a bit busy these past few days, but if you need more help - let me know ;)

**Comment by skinnymeat** [comment]
thank you
