### ISSUE TITLE
Listening for GameProcessCreation

### ISSUE THREAD

**Issue by EmilRainero** [alvyxaz/barebones-masterserver#46]
I have a custom module that asks the Spawner to start up a game process.
I wanted an listen for an event when the Game Process was created.
I had to extend SpawnersModule HandleGameProcessCreated method to invoke an event. 

I realize you are working on v2.0. You might want an OnGameProcessRegistered event on SpawnersModule. 

If there is a better way to do this of course ignore this suggestion.

**Comment by alvyxaz** [comment]
Added `SpawnersModule.SpawnedProcessRegistered` event to V2.0 ;)
