### ISSUE TITLE
ClientSocketUnet throws errors after Disconnect

### ISSUE THREAD

**Issue by EmilRainero** [alvyxaz/barebones-masterserver#47]
After disconnecting, a large number (>1000) of errors are thrown:

host id {0} has been already deleted
UnityEngine.Networking.NetworkTransport:ReceiveFromHost(Int32, Int32&, Int32&, Byte[], Int32, Int32&, Byte&)
Barebones.Networking.ClientSocketUnet:Update() (at Assets\Barebones\Networking\Scripts\ClientSocketUnet.cs:277)
Barebones.Networking.BmUpdateRunner:Update() (at Assets\Barebones\Networking\Scripts\BmUpdateRunner.cs:53)

[C:/buildslave/unity/build/Runtime/Networking/NetworkingV1/UNETManager.cpp line 695] 
(Filename: Assets/Barebones/Networking/Scripts/ClientSocketUnet.cs Line: 277)

The problem is that the Update method has a do/while loop that never exits if there is an error.

My fix was to do the following

In Update()

                if (_socketId == -1)// EMIL Fix
                    break;

                networkEvent = NetworkTransport.ReceiveFromHost(_socketId, out connectionId, out channelId, _msgBuffer,
                    _msgBuffer.Length, out receivedSize, out error);

In HandleDisconnect()

            Status = ConnectionStatus.Disconnected;
            IsConnected = false;
            _socketId = -1; //EMIL Fix

**Comment by alvyxaz** [comment]
Thanks again! 

I'll include your fix to the next update ;)

**Comment by EmilRainero** [comment]
As my clients end the game, they drop the connection to the game server.
