### ISSUE TITLE
Cannot connect to my VPS

### ISSUE THREAD

**Issue by DJCookiez** [alvyxaz/barebones-masterserver#52]
Whilst testing the Demo out, i edited it so i have a master server separate and i have the client with just the connection, i've set up the IP to the IP of my VPS and i kept the port the same, however when i run the server on my VPS with the .bat file (Server.exe -bmMaster -bmSpawner -bmIp xxxxxxxx:5000
pause)  it open the server, and everything is fine but when i goto the client on my pc not the VPS it doesn't connect, i think i set it up wrong?

**Comment by alvyxaz** [comment]
Hey!

Sounds like you did everything correctly.

Check if you've set the IP to master server correcly, in the hierarchy of the client's main scene - `Barebones/Connection`. 

If you did, and if it still can't connect, it's very likely that there are some firewall related issues on your VPS.

Also, try pinging the IP address of the master server on your computer. It's not much, but there have been a few cases where people used a wrong IP address, or were completely blocked by a firewall.

If you can, you should probably wait a couple of days until the release of V2.0 - it should be a bit easier to set up :)

**Comment by DJCookiez** [comment]
I pinged it fine, i'll check the firewall now

**Comment by DJCookiez** [comment]
Thanks i fixed it by allowing the app through the firewall now i can connect! Thanks i can't wait for V2 ! 👍
