### ISSUE TITLE
v1.03 GameServer keeps failing 

### ISSUE THREAD

**Issue by DeadlyCobraXXX** [alvyxaz/barebones-masterserver#55]
Hello!
Currently using v 1.03 until 2.0 is fully documented.
I am having difficulty launching the actual game server (my own, not Unet) from the lobby after hitting start. The lobby is 100% through the MasterServer and works perfectly. However, when everyone is ready and we click play, the server attempts to launch the game and the server and gives an error. Failed to start game server. Once the error is closed on the serverside, the lobby resumes with the 2nd error picture below. See both pictures below of the errors. I also have all of the latest updates on the server as stated in the error, btw.
![](http://i.imgur.com/gVYJhDL.png)
![](http://i.imgur.com/ghr3m82.png)
When ran in debug mode, it shows a new process of MasterServer.exe running and trying to launch "Game Room" scene, which then displays the error in the first picture above. However, I changed all the settings in the overrides to load COTR.exe at the COTR game scene.

I currently am using two scenes within the same project for the MasterServer. (2nd is Game Scene)
The first scene, which is the default MasterServer scene with all the connection profiles. See picture link.
![](http://i.imgur.com/75aL5dC.png)

SpawnersModule Settings:
![](http://i.imgur.com/1rNu3xb.png)

GamesModule Settings:
![](http://i.imgur.com/k17Y6xv.png)

SpawnerServer Settings:
![](http://i.imgur.com/b6RhPUG.png)
Both Command lines within those settings read:
C:\Users\Administrator\Desktop\COTR.exe.lnk    <- Had to use a shortcut to use command lines.
-bmStartSpawned -bmScene COTR -nographics -batchmode
COTR.exe is identical to the client version.
COTR is the game scene. (I also have the same identical scene within the MasterServer.)

Command line of MasterServer reads:
C:\Users\Administrator\Desktop\MasterServer\MasterServer.exe -bmMaster -bmSpawner -bmIp 68.1.75.164:5000 -nographics -batchmode

Client Lobby Scene Contains:
![](http://i.imgur.com/LDFLA5c.png)

All ports are open on the router. Windows Firewall is off.
p.s. Sorry for the book. Just wanted to have all the information here on the first post. I've been trying for days. I really hate to bug you.

**Comment by DeadlyCobraXXX** [comment]
I found that if logging into the server with a display attached, it loads the server, runs it on the server display, but no users are able to load the scene on the client. Also, this means I currently have to have a display plugged in and on in order for the Server to launch with the above settings. Is there a script that I'm missing to make the exe run in batch mode all the time? The lnk shortcut lines are not being applied, even with the above settings.

**Comment by alvyxaz** [comment]
Hey! Sorry for replying so late, and thanks for providing so much info!

I'm driving home now, and will reply in a couple of hours.

**Comment by DeadlyCobraXXX** [comment]
I think part of the problem is linked to the lobbyfactories.
At least the scene map was. I missed that when creating a factory, but that's updated now. However, the rest remains.

**Comment by DeadlyCobraXXX** [comment]
Also found another problem. When creating multiple "game servers", only one is actually created. The rest are started AFTER the initial game server process closes.

**Comment by alvyxaz** [comment]
When starting the spawner, add a "-bmBatchmode" argument so that spawned servers are actually started in batchmode. I've added this argument in case someone wanted to run spawner in batchmode, but not the game servers (for debugging and etc.)

If it still doesn't work, the problem is probably a missing -nographics arg when spawning a server. I thought that when you're running in batchmode, it's automatically running with "nographics". Since I'm mainly working with Linux headless build, which is by default "without graphics", I've never stumbled upon this :/.

Open the `SpawnerServer.cs` , add "-nographics" at line ~410, and let me know if this fixes the problem with DirectX initialization. If this works, I'll add the fix to the release.

![image](https://cloud.githubusercontent.com/assets/3227731/24078314/025d188e-0c73-11e7-85b1-da2c9a0e8a29.png)

----

Regarding the "only one game instance being spawned" - I'll try to reproduce this and get back to you

**Comment by alvyxaz** [comment]
I've tried to replicate the issue, where only a single game server instance was spawned at a time, but without luck - I can run multiple game servers from both lobby, and by "creating a game severs".

Just to be clear, you meant that you need to wait one game server to close, otherwise another won't spawn? Or did you mean that just after one server stars, another can "start starting", in which case you can have multiple game servers running, but they can't spawn concurrently?

**Comment by DeadlyCobraXXX** [comment]
Thank you for the reply! I'll test it out and let you know how it works.

**Comment by DeadlyCobraXXX** [comment]
Ok, your solution above works, but I have to have both changes in effect. -bmBatchmode in the command line, and -nographics in the script. However, once the gameserver is spawned, the lobby (client) does not load into the scene still. I'll have to do some more investigating as to why.

**Comment by DeadlyCobraXXX** [comment]
A couple things. I've duplicated my projects (MasterServer and ClientGame) to start the process merge to MSF v2.0. To differentiate what's going on with the two versions within my game, please see below.

ISSUE #1:
v1.03, game server tries to spawn the incorrect .exe that's listed in SpawnServer Module under SpawnerServer script. http://i.imgur.com/FfESw1D.png Doesn't matter what you put in these fields, it always spawns from the original MasterServer.exe instead of the GameServer.exe or whatever you put in there.
v2.0 Fixes this issue, and allows you to place any Exe path, and it will run with the correct settings.

ISSUE #2:
v1.03, upon hitting play from the lobby, the game server (which would be a repeat of the MasterServer.exe in this version due to Issue #1) launches successfully, but does not move the lobby members to the assumed loaded server scene. (Which is set to be an exact duplicate of the client version).
v2.0 Hitting play launches the correct GameServer.exe from the selected path, however, it closes itself semi-immediately and then returns the play buttons within the lobby back to defaults. Then it displays a failure to launch a game server.

ISSUE #3:
v1.03, upon entering and submitting text in the lobby chat, it is successfully posted, and everyone can see it. However, a Error: Timeout will appear approximately 20-30 seconds post the message being sent.
v2.0 Fixes this issue, as I've not noticed any errors being displayed other than failed server launches. 

ISSUE #4:
v2.0 only: When launching a MasterServer with command line "C:\Users\Administrator\Desktop\MasterServer2.0.exe -msfIp 68.1.75.164:5000 -msfStartMaster -msfStartSpawner -batchmode -nographics" The spawner will not activate properly without using another script similar to DemoMasterSpawnerScene.cs which was used in the DemoScene you've provided. All buttons need to be mapped. With all these mapped and enabled, everything starts automatically and correctly with the above command line.


Notes: I've been doing a lot of testing and messing around to get everything working on my end, and I can't seem to get a game server started properly. I'm probably missing something silly, but I'll continue to post bugs/my mistakes/errors as I find them. I love the new improvements found in v2.0, however, at this time using 1.03 would be a lot easier for me as the whole switch over process seems like it'll take a while including rewriting several of my own scripts due to them using functions, values/variables from v1.03, but I'm all for doing the full sweep and move to v2.0 soon. I'm really thankful that you've taken the time to help out your customers. It says a lot!

**Comment by alvyxaz** [comment]
Thanks a lot for reporting these issues! I'll go though all of them (both in this post and the other), fix them, and release an update.

By the way, I have a suggestion regarding the batchmode and nographics arguments:

Do you think it would be better if by default, spawned games copied **-batchmode**  and **-nographics** from the spawner (they would be started using these args if spawner was started with them). And for the cases where user doesn't want spawned game servers to be in batchmode, he would have to provide an argument "**-dontSpawnInBatchmode**" or something similar

**Comment by alvyxaz** [comment]
**ISSUE 1**:

When running the spawner server, it always overwrote the path with a value, provided through command line arguments, and when there was no command line value provided - it automatically used a default value of the argument. I became aware of that when working on V2, but it didn't cross my mind to fix it on V1.03.

So you can provide a path via argument, like `-bmExe D:/sfsfs/ssfs.exe`, and it should use that value.

Or a more proper fix would be to change the `ExtractCmdArgs()` method, like this:

`SpawnerServer.cs`, line ~309. 

![image](https://cloud.githubusercontent.com/assets/3227731/24092345/6e20fc1e-0d56-11e7-98e0-1a1a5b23ab31.png)

Same thing applies to all of the arguments in that method

**Comment by alvyxaz** [comment]
**ISSUE 3:**

Apparently, in V1.03 lobby chat, I made it send a message and wait for a response. However, API was designed to not give any response. The easiest fix would probably be to send a response from server, if user expects to get it:

`GameLobby.cs, HandleChatMessage()` Line ~ 850

![image](https://cloud.githubusercontent.com/assets/3227731/24092754/e9421944-0d58-11e7-8ab8-23cc00b192fc.png)

**Comment by alvyxaz** [comment]
**ISSUE 4:**

Spawner server relies on connection to master server. It will start only when the connection to master server is established.

`SpawnerBehaviour` itself has no means to connect to master, it only waits for the connection. To connect to master, you can drag in a `Barebones/Msf/Prefabs/ConnectionToMaster` prefab to the scene, and it should fix the issue.

I'll include this notification to documentation ASAP, as I agree that it's not very obvious. I'll also add a hint about this at the `SpawnerBehaviour` component

**Comment by alvyxaz** [comment]
Regarding **ISSUE 2**.

Do you think you could zip your project, and send it over to alvyxaz@gmail.com? It's probably has something to do with the setup. I'll try to find what's wrong, fix it, and probably add a notification to docs, or find a way to avoid this in future versions of the framework

**Comment by DeadlyCobraXXX** [comment]
> Thanks a lot for reporting these issues! I'll go though all of them (both in this post and the other), fix them, and release an update.
> 
> By the way, I have a suggestion regarding the batchmode and nographics arguments:
> 
> Do you think it would be better if by default, spawned games copied -batchmode and -nographics from the spawner (they would be started using these args if spawner was started with them). And for the cases where user doesn't want spawned game servers to be in batchmode, he would have to provide an argument "-dontSpawnInBatchmode" or something similar

Yes! I think most devs would appreciate this, as I can't think of a time where we would want a dedicated server to run outside of batchmode, but for those who do, they'll have that command arg.

**Comment by DeadlyCobraXXX** [comment]
I think today, I'll focus on completing my merge to v2.0 because that's going to be the new baseline, but also because of the new features. It also fixes some issues out of the box, like the chat (issue 3) and spawner exe path (issue 1). All in all, I think you're doing an excellent job, and I'm very happy I went with MSF. Thanks again! I'll post further updates as I move along this process.

As far as fixing Issue 2, I'll have to do a major clean-up of my project before .zipping due to it being in pieces with the recent changes between v1.03 and v2.0, as well as some other coding/assets I've used previously for networking. It might be a little while, but I appreciate the thought to help try to solve my case!

**Comment by DeadlyCobraXXX** [comment]
Update: My merge to v2.0 is done. I have just two scripts to rewrite for the new api. 
A Profile variables/properties script and a custom lobby "Update CrownMaster" script which applies a crown graphic to the Lobby Master.

I've also cleaned up a lot of my project, so it shall be ready for a .zip in another day on my day off from work.

May I please request the "Profiles" section in your documentation be completed soon, as that would save me time and help relearn v2.0's new api/commands regarding the profiles.

Thanks in advance!!!

**Comment by alvyxaz** [comment]
Hey!

Sure, I can cover profiles today ;).

I'll get back to you with other issues in a few hours

**Comment by alvyxaz** [comment]
I rewrote the profiles page for V2.0:
https://github.com/alvyxaz/barebones-masterserver/wiki/Profiles-Module

By the way, I remember seeing your post that you had difficulties trying to get username of the player. Since the post is gone, I guess you found it? I would like to improve that, so other developers don't need to spend hours looking for it. I was wondering if you have any suggestions on how to make it better? Were you struggling to get a username on master server, client or game server?

**Comment by RowellKataan** [comment]
Couldn't you easily find the player's name using the Msf.Client.Auth.AccountInfo.Username inside your game?

**Comment by DeadlyCobraXXX** [comment]
> By the way, I remember seeing your post that you had difficulties trying to get username of the player. Since the post is gone, I guess you found it? I would like to improve that, so other developers don't need to spend hours looking for it. I was wondering if you have any suggestions on how to make it better? Were you struggling to get a username on master server, client or game server?

I did find it :), but it took a while because I tried all the obvious ones I could think of including Msf.Client.Auth.AccountInfo.Username, but I must have had typed something wrong because after retrying it later on, it worked. I also found that you had posted that information in your documentation, but it wasn't until after I got it working before I found it lol.

I don't think any improvement is necessary there, I just think I did something wrong initially which is what led me to having to search broader. But it was on the client version, the easiest one to retrieve lol.

Also, thanks so much for doing the Profiles-Module documentation! I just got home from work, and I'm tired, so I'll mess with that tomorrow.

**Comment by DeadlyCobraXXX** [comment]
@alvyxaz Hey bro, I didn't forget about this post. I've just been busy with work. I'll .zip a copy to you real soon to help with this issue I'm having. Probably Monday-ish.

**Comment by alvyxaz** [comment]
Sure, no need to rush - i'm not going anywhere ;)

**Comment by DeadlyCobraXXX** [comment]
Sending you the link to download the Project files via e-mail today. Currently zipping them up. 4 GB...
I will upload it to DropBox. I left a README and some other documentation in the base of the project folder. If you have any questions, I'll be around all day tomorrow (4/6/17). I can join your discord at that time too. I probably will be in there regardless to discuss any issues.

Thanks a bunch man, you're a total lifesaver!

**Comment by DeadlyCobraXXX** [comment]
FYI, I just got a VPS (for testing purposes), and am in the process of setting it up...
It's pretty much done now, BUT since the files I sent to you via E-mail contains the IP addresses for a local MasterServer, you'll have to download the latest patch via the updater (Launcher). I'll patch it tomorrow (4/6/2016) to reflect the new VPS IP. In the meantime, I'll leave my local server up and online, so you can connect and do whichever you'd like without having to edit any project files other than MSF. I'll also make you a user on the VPS, so you can login if you need to.

Sorry this is so complicated.... :\

**Comment by DeadlyCobraXXX** [comment]
![](http://i.imgur.com/04wJARx.png)
This should say "-msfStartSpawner"

Also, after looking into what you said, I am still unable to change scenes.
I am fully upgraded to v2.0.3 now, added the unet connector to the lobby scene too.
Everything matches from what you have in the QuickSetup, but with my server settings such as IP, Port, and GameServer Path. I still do not have any luck. I scrapped my own MasterServer scene and am currently using the one from the QuickSetup in hopes to find it magically working lol. But it still isn't. :(

My GameServer scene is identical to yours as well.

Client "Create Server" and "Create Lobby" settings reflect my game scene map as well.

I'm just stuck again and out of ideas as to why it just won't load in. I can allow you access to my Team Collab if you'd like. Maybe that would make things easier to look at...

**Comment by DeadlyCobraXXX** [comment]
After looking over a few more things, I may have found a couple other things I forgot, however, it's bedtime now. I did send you a request to your email as a User to my Organization so you can view it if needed to.

I'll try again after work tomorrow. Have a good night!

**Comment by alvyxaz** [comment]
Hey!

Today's my day off, so I'll look into what might be happening with more
details tomorrow.

To progress faster, I'd recommend to create a smaller project with
something like a "fake" unet game, so that you can build/test your
client/game server faster.

Of the top of my head, here's the flow of events that should happen:

* When you hit "play" in the lobby, spawner should receive a request to
spawn a game server, so make sure that it does
(SpawnerController.DefaultSpawnRequestHandler should be called)
* New process should be started (make sure that it does). If it doesn't,
spawner probably has a wrong path to .exe of game server
* Game Server scene should be loaded - if it's not, there's probably no
script in the main scene to switch scenes. You could add
Barebones/Msf/Prefabs/SimpleBootstrapper which does that, or load a new
scene manually (see how it's done in the Demos/QuickSetup/Scenes/GameServer)
* Game server should be started (add NetworkManagerHUD to scene, which
should give you more info on whether or not the game server was actually
started )

**Comment by DeadlyCobraXXX** [comment]
Ok, I've done as you asked and made a smaller project. The smaller project works. I've applied the same settings and gameobjects to my current project, and I'm still getting failed to create server.

The gameserver process runs, after about so many seconds, it closes and displays failed to create a game server on the client chat ui.

I've been messing around with this for days and still cannot find the reason to why this isn't working on my real project. Makes no sense.

**Comment by DeadlyCobraXXX** [comment]
[output_log.txt](https://github.com/alvyxaz/barebones-masterserver/files/910701/output_log.txt)
Here's my MasterServer/Spawner Output log.

**Comment by DeadlyCobraXXX** [comment]
It looks like it gets to Process registered (4/5) before your default UI (Progress) says Aborted.

**Comment by DeadlyCobraXXX** [comment]
Update:
After rebuilding my entire GameServer Scene and re-mirroring all the settings it had before, I am able to create and join a server successfully. The scene changes too. However, when I click "Start Game" in the lobby when everyone is ready, I am having the previous issue. The GameServer launches, but does not change scenes, nor detect a scene change.

**Comment by DeadlyCobraXXX** [comment]
Omg, I'm so stupid. I got it working perfectly now.
