### ISSUE TITLE
Lobby Question

### ISSUE THREAD

**Issue by DeadlyCobraXXX** [alvyxaz/barebones-masterserver#61]
Is there an easy way to call the name of the lobby game master in v2.0?

Previously, in 1.03, I called 
```
public LobbyView LobbyView;
LobbyView.RawData.GameMaster.ToString()
```
from a custom script.

**Comment by alvyxaz** [comment]
When user joins a lobby, he receives an instance of `JoinedLobby`, which has pretty much all of the state information, including the initial data:

`JoinedLobby.Data.GameMaster`

If you're using `LobbyUi`, it has a property `LobbyUi.JoinedLobby` - which is the instance of `JoinedLobby`. 

In fact, lobbyUi is drawn almost entirely from what's accessible through `JoinedLobby`. 

I didn't yet cover lobbies API in documentation, but here's a quick snippet which shows how it works:

``` C#
Msf.Client.Lobbies.CreateAndJoin("2vs2vs4", new Dictionary<string, string>(), (lobby, error) =>
{
    // -----------------------
    // Use 'lobby' to get all of the data
    var gameMaster = lobby.Data.GameMaster;

    // -----------------------
    // Or here's an example on how this lobby is used to draw information to UI

    var lobbyUi = FindObjectOfType<LobbyUi>();

    // Set lobby ui as a listener of lobby events (joined users, changed
    // properties and etc) 
    lobby.SetListener(lobbyUi);

    // Setup initial UI
    lobbyUi.Setup(lobby);

    // Display the lobby UI
    lobbyUi.gameObject.SetActive(true);
});
```

**Comment by DeadlyCobraXXX** [comment]
This worked.
I was able to get it easily with `LobbyUi.JoinedLobby.Data.GameMaster.ToString()`
Thank you!
