### ISSUE TITLE
Exposure to Logged In Users (from Master Server)

### ISSUE THREAD

**Issue by RowellKataan** [alvyxaz/barebones-masterserver#64]
I might be missing it somewhere, but is there any exposure to list the users currently connected to the master server?  I see a dictionary in the Auth module, as well as the look up a user by peerID.  However, I don't see a means to access the dictionary/data from outside the auth module.

**Comment by RowellKataan** [comment]
Apologies.  Found a way to do it.  Auth.LoggedIn and Auth.LoggedOut events to track who is logging in and logging out.

**Comment by alvyxaz** [comment]
I guess you wrote a custom module, which tracks the current number of logged in users?

I wonder if I should publicly expose `LoggedInUsers` for easier access

**Comment by EmilRainero** [comment]
It would help. I had a section in my custom UI prefab to show the # of authorized users, probably the best single statistic on the state of the masterserver after  if it is running. That's were I was tracking based on LoggedIn/LoggedOut events.

**Comment by RowellKataan** [comment]
My Master Server has two listboxes; one to list all the connected and authenticated users, and one to list all the instances (rooms).   In my Instances list, I list the room name along with the player count/player max.  In my user list, I list the user name, along with the instance (room) they are in (if they're not in a room, I just list the username).

I had to add a pair of Actions/Events to track connections by peer as well as by room.  That way, I can detect and change both my listboxes when a player joins and leaves a room.

Exposing the player list would be very helpful.  I didn't spend a lot of time working through my method of getting the information, but having a handy-dandy list at my fingertips would have saved time.

The more I dive into your code, the more I appreciate it.
