### ISSUE TITLE
Zone servers not reachable in Batchmode

### ISSUE THREAD

**Issue by Specro777** [alvyxaz/barebones-masterserver#65]
(To save future readers of this post, the solution was discovered, and posted in the first reply)

Hello! I've been pouring myself over the Master server to learn the ins and outs of its functionality, and I've been loving it thus far. However, while trying to work on setting up the framework in my prototype, I've run across a concerning issue. 

For context, I am using the World Demo as a basis for my prototype (as that is precisely what I will be using it for). I am using Version 2.0.1 (Micro Update)

Everything operates perfectly. The Master Server goes online, and the spawner server follows, generating two instances of unity for two areas being supported. I am able to connect to them, play on them, etc. Everything is great. 

However, when I switch the zone servers to run in batchmode, things aren't so great. I've run the Master Server in Batchmode via argument in a bat file, and I have the game servers being spawned in batchmode via the setting in the Spawner prefab (using SpawnerBehavior.cs). 

When running in Batchmode, the servers all go online report being online, and are all properly in batchmode. However, while I can log into the Master Server, it stops there. I cannot actually get into a zone. The server reports: 

`[Error | Logs] Failed to enter the world: Zone not found`

If I change absolutely nothing, and switch it back from running in batchmode, everything will work as intended. This is the case with my own project running my own code, as well as running the World Demo with no alterations. The Master Server can be in batchmode, but if the Zone servers are, they are not reachable. 

Here is the log of the servers coming online, and my subsequent attempt at logging into them. Ignore my failed attempt at first, my UI is... imperfect. 
http://pastebin.com/tMW9f78U

Any assistance is greatly appreciated. Hopefully someone has a solution, and if not, one can be generated. Thank you for any help you can offer!
-Specro

**Comment by Specro777** [comment]
Given enough time and determination I managed to solve the issue. I double checked to see if it was my own work that had flubbed it up, but, I'm not entirely sure, as the issue is present in a fresh install. 

The entire problem was with line 221 in SpawnerController.cs

`(controller.DefaultSpawnerSettings.RunInBatchmode ? "-batchmode -nographics" : "")`

The lack of a space at the end of -nographics causes the next argument in line, "-msfLoadScene" to basically merge and become "-nographics-msfLoadScene" which isn't read by the argument reader in the framework, and therefore fails to load the scene entirely. 

The issue is resolved by adding a space at the end of -nographics.

`(controller.DefaultSpawnerSettings.RunInBatchmode ? "-batchmode -nographics " : "")`

It's always the little things, isn't it?

**Comment by RowellKataan** [comment]
SPACES!!!  *Fist shake*

**Comment by alvyxaz** [comment]
@Specro777 Darn, this is embarrasing! I'm really sorry for having you spend you'r time on this issue, 

This is a rather nasty bug, so I'll add the fix to the V2.0.2, and push it to the asset store today (not sure how long it's going to take to get approved)

Thanks a lot for finding the issue!

**Comment by Specro777** [comment]
Don't sweat it! It fortunately didn't take too long to solve, and I am happy to have helped contribute, even in a small way, to this awesome framework.
