### ISSUE TITLE
help me to setting up

### ISSUE THREAD

**Issue by parthshivlab** [alvyxaz/barebones-masterserver#67]
hello i have updated new version of master server, but cannot use as i want, please help me to solve it

**Comment by alvyxaz** [comment]
Hey! 

Are you sure that the master server is started?
Is it running on your computer, or somewhere else?

Did you try the Quick Setup?
https://github.com/alvyxaz/barebones-masterserver/wiki/Quick-Setup

Are you sure that you're using V2? When you download framework from asset store, it defaults to V1.03. For V2, you'll need to use the  `BM V2.0.x.unitypackage`

**Comment by parthshivlab** [comment]
yes i startup., and i used V2

**Comment by parthshivlab** [comment]
and why i cannot connect game globally. its working only in same wifi area

**Comment by parthshivlab** [comment]
hello, cannot work demo in my mac, please help to solve it.
