### ISSUE TITLE
Disable guest login

### ISSUE THREAD

**Issue by tertle** [alvyxaz/barebones-masterserver#7]
Would be nice to have a simple toggle on the authmodule to disable guest logins on master server. Simply removing the UI element isn't good enough as a user with a hacked client could still call Auth.LogInAsGuest(...) themselves.

I could override the authmodule myself and pass in my own LoginUserHandler instead to remove it but it seems like a useful general feature.

**Comment by alvyxaz** [comment]
This is a great request!

I'll include this functionality in the next release ;)

**Comment by alvyxaz** [comment]
V1.03, `AuthModule.EnableGuestLogin`
