### ISSUE TITLE
Errors when deleting demo directory

### ISSUE THREAD

**Issue by GMichl** [alvyxaz/barebones-masterserver#73]
Hi,
not sure if thats really an issue or just I'm doing something wrong.
I want to learn how all peaces of the framework are working together by creating all the scenes from scratch.
I like to have such projects clean, without any documentation/demos in it. So after importing the whole framework I have deleted the "Demos" directory and now the console shows the following error:
```
Assets/Barebones/Msf/Scripts/Modules/Rooms/MsfRoomsClient.cs(116,21): error CS0103: The name `RoomConnector' does not exist in the current context
```
The documentation says the Msf directory contains the core components of this framework.
So for me it looks like the core components have dependencies to the demo files.

**Comment by alvyxaz** [comment]
Hey!

Try to move 

`Barebones/Demos/RoomsDemo/Scripts/RoomConnector.cs`

to 

`Barebones/Msf/Scripts/Modules/Rooms/.`

If you do that, you should be able to delete the whole `Demos` folder and `MsfUiSamples`.

I thought that I pushed this change to V2.0.2, but I probably didn't :/

**Comment by arcanor** [comment]
I have 2.0.2 and I already have this file in the correct location (Barebones/Msf/Scripts/Modules/Rooms/)

**Comment by GMichl** [comment]
Thank you for the response.

Moving
```
Barebones/Demos/Common/Scripts/RoomConnector.cs
```
to
```
Barebones/Msf/Scripts/Modules/Rooms//RoomConnector.cs
```
Solves the issue.

**Comment by alvyxaz** [comment]
@GMichl Great! ;)
