### ISSUE TITLE
Bug:  OnUserDisconnect event not firing

### ISSUE THREAD

**Issue by RowellKataan** [alvyxaz/barebones-masterserver#75]
I've noticed that the OnUserDisconnect event and invoke are not firing when a user logs off.  (I'm looking primarily in the AuthModule).   I have a method that adds users to a ListBox when they log in, and remove them from a ListBox when the log out.  The log out portion is not working due to the OnDisconnect event not firing.

**Comment by RowellKataan** [comment]
Update:   It seems that the OnUserDisconnect (in AuthModule) is not firing when running as a compiled application  (I'm compiling to Windows 64bit) as a Master Server.  When I run the master server in the editor, and connect to it from an .EXE client, OnUserDisconnect is firing properly.  However, when the master server is running as a compiled EXE file, and I connect to it with a client running in the Unity Editor, the OnUserDisconnect event isn't firing at all.

**Comment by arcanor** [comment]
I have noticed this as well. When I run my client from a Unity Editor instance, the master server (on another computer) doesn't detect the client disconnect until I restart the client inside the editor, or terminate the editor entirely.

**Comment by alvyxaz** [comment]
Woah. Thanks for reporting this. I'll take a look at it tomorrow and submit
a fix ;)

**Comment by RowellKataan** [comment]
Thanks a bunch!

**Comment by arcanor** [comment]
I'm not sure if this is a MSF bug or a Unity Editor bug. It would seem like the Editor is holding connections open when it shouldn't (i.e. after Play Mode is stopped).

**Comment by alvyxaz** [comment]
@arcanor You're right - I just looked into it, and it does seem like the editor is holding the connection, and it happens only when client is running from withing the editor.

To fix this, you can add this code to `ConnectionToMaster.cs`:

``` C#
void OnApplicationQuit()
{
    var connection = GetConnection();

    if (connection != null)
        connection.Disconnect();
}
```

I've pushed this fix to repository, it will be available in the V2.0.4 release, which is when I'll close this issue ;)

**Comment by RowellKataan** [comment]
Eggscellent!  Thanks!

**Comment by RowellKataan** [comment]
Yup, that's got it fixed.
