### ISSUE TITLE
[Error | Logs] Failed to enter the world: Zone not found

### ISSUE THREAD

**Issue by UnityEQ** [alvyxaz/barebones-masterserver#77]
Just started on this, thanks for open sourcing it!

Anyway, I'm running Unity 5.6.0f3. After logging in, than hitting "Enter World" I get the error below. Not sure why.

[Error | Logs] Failed to enter the world: Internal Server Error
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Barebones.Logging.LogAppenders:UnityConsoleAppenderWithNames(BmLogger, LogLevel, Object)
Barebones.Logging.BmLogger:Log(LogLevel, Object)
Logs:Log(LogLevel, Object)
Logs:Error(Object)
WorldDemoMainScene:<OnEnterWorldClick>m__0(ResponseStatus, IIncommingMessage) (at C:\\Documents\Mapboxv4\Assets\Barebones\Demos\WorldsDemo\Scripts\WorldDemoMainScene.cs:31)
Barebones.Networking.BasePeer:TriggerAck(Int32, ResponseStatus, IIncommingMessage) (at C:\\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\BasePeer.cs:356)
Barebones.Networking.BasePeer:HandleDataReceived(Byte[], Int32) (at C:\\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\BasePeer.cs:383)
Barebones.Networking.ClientSocketWs:Update() (at C:\\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\ClientSocketWs.cs:177)
Barebones.Networking.BmUpdateRunner:Update() (at C:\\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\BmUpdateRunner.cs:53)
 
(Filename: C:/Documents/Mapboxv4/Assets/Barebones/Demos/WorldsDemo/Scripts/WorldDemoMainScene.cs Line: 31)

**Comment by UnityEQ** [comment]
Figured it out by looking at MsfQuickBuild. Defaults off of QuickSetup when I was using WorldsDemo

**Comment by arcanor** [comment]
It looks like you haven't set up your database correctly yet. You'll need to create the database and add the tables needed by MSF. You can do this by running the SQL text file that comes inside the MySql.zip file (file is called 'SQL (MAKE BACKUPS OF YOUR DB!).txt').

**Comment by UnityEQ** [comment]
I have

![have](https://cloud.githubusercontent.com/assets/4616265/25316386/2a29bcfa-281b-11e7-8dba-fe859e36c4a8.png)

**Comment by arcanor** [comment]
OpCode 101 is not a standard MSF opcode. Those all start above 32000. Take a look at MsfOpCodes.cs. OpCode 101 must be a custom one that you created yourself? If so, then you need to have a corresponding module in your master server to handle those requests.

**Comment by UnityEQ** [comment]
This is a fresh install, only thing I did was change IPs and added mysql

**Comment by arcanor** [comment]
Sorry but I have not tried that demo. Maybe @alvyxaz or someone else can assist?

**Comment by arcanor** [comment]
Actually, I've just glanced over the code quickly and it seems that the handler is defined in WorldDemoModule. In the WorldDemo-MainScene, that class is NOT a child of the MasterServer gameobject. I'm going to take a wild guess here and ask if maybe you have set the MasterServer in that scene to "Look in children only" ? That would make it so that the WorldDemoModule would not be found.

**Comment by UnityEQ** [comment]
Figured it out, my server was from quicksetup where my client was from worldsdemo >_<

New error that im working through below

[Error | Logs] Failed to enter the world: Zone not found
UnityEngine.Debug:LogError(Object)
Barebones.Logging.LogAppenders:UnityConsoleAppenderWithNames(BmLogger, LogLevel, Object)
Barebones.Logging.BmLogger:Log(LogLevel, Object)
Logs:Log(LogLevel, Object)
Logs:Error(Object)
WorldDemoMainScene:<OnEnterWorldClick>m__0(ResponseStatus, IIncommingMessage) (at Assets/Barebones/Demos/WorldsDemo/Scripts/WorldDemoMainScene.cs:31)
Barebones.Networking.BasePeer:TriggerAck(Int32, ResponseStatus, IIncommingMessage) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:356)
Barebones.Networking.BasePeer:HandleDataReceived(Byte[], Int32) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:383)
Barebones.Networking.ClientSocketWs:Update() (at Assets/Barebones/Networking/Scripts/ClientSocketWs.cs:177)
Barebones.Networking.BmUpdateRunner:Update() (at Assets/Barebones/Networking/Scripts/BmUpdateRunner.cs:53)
