### ISSUE TITLE
Players not spawning (modified QuickSetup scene)

### ISSUE THREAD

**Issue by TechieCrow** [alvyxaz/barebones-masterserver#78]
First off, yes I know I'm not suppose to edit the QuickSetup scenes directly, I'm doing it for now to test.

So first I checked to see if QuickSetup was working correctly without any changes and indeed it worked with no problems then I swapped out the level and player prefab but now (with all other settings the same) I am getting this error:

```
Failed to spawn server object, did you forget to add it to the NetworkManager? assetId=ae0a4d88ab925784bb21366c30a54b70 netId=2
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate()
```

After Googling the problem everyone was saying to add the prefab to NetworkManager as a registered spawnable prefab which I had already done, I have even look at a few of the scripts but they don't seem to be causing a problem with my own player prefab, any ideas?

**Comment by icewiski** [comment]
same problem.
i replaced my playerprefab with the miniplayer in demo minigame,and it wouldn't work too.
i think it's owe to the high level api of UNET.

**Comment by alvyxaz** [comment]
At the moment I can't test it, but this behaviour seems quite strange.

You should probably try creating a new scene with very basic Unet setup (no framework integration yet). Make a build with it, and test if player can be properly spawned.

If it works, use the similar setup as is used in the `SimplePlatform` scene to integrate the framework :)

**Comment by TechieCrow** [comment]
Unet works fine on it's own in my scene.

I have noticed in the `MiniNetworkManager`:
```
/// <summary>
    ///     Spawns a character for connected client, and assigns it to connection
    /// </summary>
    /// <returns></returns>
    public static MiniPlayerController SpawnPlayer(NetworkConnection connection, string playerName, 
        string weaponSprite, Transform position = null)
    {
        // Create an instance
        var player = Instantiate(Resources.Load<MiniPlayerController>("Prefabs/MiniPlayer"));

        if (position == null)
        {
            // Nove to random position, of no position was given
            player.MoveToRandomSpawnPoint();
        }
        else
        {
            player.transform.position = position.position;
        }

        NetworkServer.AddPlayerForConnection(connection, player.gameObject, 0);
        player.SetWeapon(weaponSprite);
        player.Setup(playerName);

        return player;
    }
```
""
I'm probably wrong but isn't that using `MiniPlayerController` and trying to instantiate `MiniPlayer` from the prefabs folder? I changed `MiniPlayer` to `Player` and moved my prefab into the same folder but then it started complaining that the object it's trying to instantiate is null.

QuickSetup is the exact setup I need so I don't really want to reinvent the wheel by making it from scratch.

**Comment by angusmf** [comment]
Are your prefabs in resources folder?

**Comment by TechieCrow** [comment]
I tried putting the player prefab in the same folder as MiniPlayer but no luck. :(

**Comment by alvyxaz** [comment]
Did you change the type of `MiniPlayerController` to your own? I mean, it should be something like this (note **MyCustomScript**):

`Resources.Load<MyCustomScript>("Prefabs/MiniPlayer")`

**Comment by TechieCrow** [comment]
I started fresh and added my own scene to `QuickSetup` using the guide on the wiki, managed to get it working! <3

Sorry for all the hassle, I'm not very good with network scripting which is why I wanted to use QuickSetup, it's setup exactly as I needed so should have been (and actually is) easy to add my own scene, change UI stuff and extend functionality, again the problem was me not being good with networking, the Wiki and Barebones Masterserver are very good! :)

Now to start implementing the rest of my game! ❤️

**Comment by alvyxaz** [comment]
Awesome, it's good to hear that you got it working! ;)
