### ISSUE TITLE
WorldsDemo: Failed to Enter World: Zone not found

### ISSUE THREAD

**Issue by UnityEQ** [alvyxaz/barebones-masterserver#79]
After setup, I successfully log in and then click enter world. The error "Zone not found" comes up and I'm unable to transition off of WorldDemo-MainScene to WorldDemo-LoadingScene or WorldDemo-ZoneMain

My build isn't custom at this point.

Server
![frame1](https://cloud.githubusercontent.com/assets/4616265/25563062/7e41ac30-2d48-11e7-9330-baa80a0e90a6.png)

Client
![frame2](https://cloud.githubusercontent.com/assets/4616265/25563063/7e42a6f8-2d48-11e7-9bc9-ebedd8aea2c2.png)

Build Scenes
![frame3](https://cloud.githubusercontent.com/assets/4616265/25563064/7e45423c-2d48-11e7-930e-362eca014ba6.png)

Client Error Log (No error serverside)
[Error | Logs] Failed to enter the world: Zone not found
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Barebones.Logging.LogAppenders:UnityConsoleAppenderWithNames(BmLogger, LogLevel, Object)
Barebones.Logging.BmLogger:Log(LogLevel, Object)
Logs:Log(LogLevel, Object)
Logs:Error(Object)
WorldDemoMainScene:<OnEnterWorldClick>m__0(ResponseStatus, IIncommingMessage) (at C:\Users\comrade\Documents\Mapboxv4\Assets\Barebones\Demos\WorldsDemo\Scripts\WorldDemoMainScene.cs:31)
Barebones.Networking.BasePeer:TriggerAck(Int32, ResponseStatus, IIncommingMessage) (at C:\Users\comrade\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\BasePeer.cs:356)
Barebones.Networking.BasePeer:HandleDataReceived(Byte[], Int32) (at C:\Users\comrade\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\BasePeer.cs:383)
Barebones.Networking.ClientSocketWs:Update() (at C:\Users\comrade\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\ClientSocketWs.cs:177)
Barebones.Networking.BmUpdateRunner:Update() (at C:\Users\comrade\Documents\Mapboxv4\Assets\Barebones\Networking\Scripts\BmUpdateRunner.cs:53)
 
(Filename: C:/Users/comrade/Documents/Mapboxv4/Assets/Barebones/Demos/WorldsDemo/Scripts/WorldDemoMainScene.cs Line: 31)

Code
![frame4](https://cloud.githubusercontent.com/assets/4616265/25563112/86f3c254-2d49-11e7-8df4-98b4addeb2c1.png)
@alvyxaz

**Comment by Specro777** [comment]
Are you running the spawner servers in batchmode? If so, you might be encountering a bug in the system that I discovered a few weeks ago. 

https://github.com/alvyxaz/barebones-masterserver/issues/65

**Comment by UnityEQ** [comment]
@Specro777 My SpawnerController has the fix in that issue, so it isn't that
(spawnInBatchmode ? "-batchmode -nographics " : "") +

![frame5](https://cloud.githubusercontent.com/assets/4616265/25567431/ebc5db74-2da1-11e7-9631-5d9ad3a3bf75.png)

**Comment by alvyxaz** [comment]
@UnityEQ Sorry for taking so long to reply - does the game server start (it should open a new Unity instance)?

**Comment by UnityEQ** [comment]
@alvyxaz No, I assume im missing a step in the setup process for worldsdemo

**Comment by UnityEQ** [comment]
Still having this problem. Major bottleneck, not sure what step im missing or what I'm doing wrong >_<

**Comment by MostHated** [comment]
I see you closed this, what was the solution? I am having the same issue. My spawnercontroller.cs has a space after -NoGraphics, but I still get the zone error. I have tried in editor, standalone, running spawner separate from master server, all kinds of things, all with the same end result. I am currently just testing locally.
