### ISSUE TITLE
chat comands return [Error] not handled message

### ISSUE THREAD

**Issue by delmarle** [alvyxaz/barebones-masterserver#8]
im using /w username message, /join name,/ch channel message

and it all works but there is those error message on client sender:

https://gyazo.com/e2a6337016253ddc8e80b4f92cfd0f0e

**Comment by alvyxaz** [comment]
I'll look into it and get back to you ;)

**Comment by alvyxaz** [comment]
Yup, I've replicated the issue. Thanks for notifying ;)

I will include the fix into v1.03, and until then:

In ChatModule.cs file, you can change line ~137 from `break;` to`return true`

![](http://i.imgur.com/z8eJhCU.png)

**Comment by alvyxaz** [comment]
Fixed in V1.03 ;)
