### ISSUE TITLE
Errors on upgrading from v1 to v2

### ISSUE THREAD

**Issue by fgurel** [alvyxaz/barebones-masterserver#89]
Hello,

When upgrading from V1 to V2 I have the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'MiniNetworkManager.OnServerAddPlayer(NetworkConnection, short)': no suitable method found to override	
Error	CS0115	'NetworkManagerSample.OnServerDisconnect(NetworkConnection)': no suitable method found to override	
Error	CS0117	'NetworkManager' does not contain a definition for 'OnServerDisconnect'	

Anyone else have these?
Thank you,
Gurel

**Comment by alvyxaz** [comment]
Did you try to install V2 on top of V1?

If it's the case, it won't work, because V2 has too many changes - it's a completely rewritten framework :)

**Comment by fgurel** [comment]
I guess I did, I removed V1 completely then imported V2 and now it works fine.

Thank you! :)
