### ISSUE TITLE
WorldsDemo: Doesn't Work

### ISSUE THREAD

**Issue by UnityEQ** [alvyxaz/barebones-masterserver#90]
https://youtu.be/b3moOxXwoWs

**Comment by alvyxaz** [comment]
I'm sorry it's taking so long to solve this. I somehow thought you'd find the solution by now :/

By the way, it says that the video is unavailable. :/

Either way, if another unity instance is not started, you should go through the code to see what exactly and why is not being called.

Try to log something at `WorldDemoModule.SpawnZoneServers` to see if this method is being called.

If not, you're either:
* Starting master server from editor, and don't have the `SpawnZonesInEditor` set to true
* Starting the master server from build, and don't have the `-spawnZones` argument

**Comment by UnityEQ** [comment]
Fixed, vid was set to private. I do: Client.exe -msfStartMaster -msfStartSpawner

**Comment by alvyxaz** [comment]
Try to add an argument `-spawnZones`

**Comment by UnityEQ** [comment]
That fixed the problem I was having. Praise to you sir.

**Comment by alvyxaz** [comment]
I'm really sorry I didn't think about asking you this from the start :/
