### ISSUE TITLE
Changing SimplePlatform Scene

### ISSUE THREAD

**Issue by fgurel** [alvyxaz/barebones-masterserver#98]
I know this may sound so easy but when I want to work with Quick Setup Demo, I want to test it with a different scene. So I specify another scene under maps for CreateGameUI as parameter instead of SimplePlatform, but when I build it I have the following error:

Scene 'SimplePlatform' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings...
UnityEngine.SceneManagement.SceneManager:LoadScene(String)
UnetRoomConnector:ConnectToGame(RoomAccessPacket) (at Assets/Barebones/Demos/Common/Scripts/UnetRoomConnector.cs:75)
Barebones.MasterServer.RoomConnector:Connect(RoomAccessPacket) (at Assets/Barebones/Demos/Common/Scripts/RoomConnector.cs:62)
Barebones.MasterServer.<GetAccess>c__AnonStorey0:<>m__0(ResponseStatus, IIncommingMessage) (at Assets/Barebones/Msf/Scripts/Modules/Rooms/MsfRoomsClient.cs:117)
Barebones.Networking.BasePeer:TriggerAck(Int32, ResponseStatus, IIncommingMessage) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:356)
Barebones.Networking.BasePeer:HandleDataReceived(Byte[], Int32) (at Assets/Barebones/Networking/Scripts/BasePeer.cs:383)
Barebones.Networking.ClientSocketWs:Update() (at Assets/Barebones/Networking/Scripts/ClientSocketWs.cs:177)
Barebones.Networking.BmUpdateRunner:Update() (at Assets/Barebones/Networking/Scripts/BmUpdateRunner.cs:53)

Where else should I specify the new scene to test the demo with instead of SimplePlatform? 
Thank you,
Gurel

**Comment by jim-freeman** [comment]
If you are using the build menu items, you will need to edit the file MsfQuickStartBuild.cs.

**Comment by fgurel** [comment]
Alright that does it, thank you!
